ministryofjustice/laa-assess-crime-forms

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/pull_request_template.md
- README.md
- Adds initial git files for the repo. This includes
- Pull Request layout
- Dependabot
- Codeowners
N/A
> Add initial git files

- Gemfile
- Gemfile.lock
- app/controllers/healthcheck_controller.rb
- config/routes.rb
- spec/controllers/healthcheck_controller_spec.rb
- spec/spec_helper.rb
Add ping endpoint which uses healthcheck#ping
[Setup Caseworker Environments](https://dsdmoj.atlassian.net/browse/CRM457-398)
> Add ping endpoint

- Dockerfile
- config/database.yml
- config/environments/production.rb
- docker-compose.yml
- helm_deploy/.helmignore
- helm_deploy/Chart.yaml
- helm_deploy/templates/NOTES.txt
- helm_deploy/templates/_helpers.tpl
- helm_deploy/templates/deployment.yaml
- helm_deploy/templates/ingress.yaml
- helm_deploy/templates/service.yaml
- helm_deploy/templates/tests/test-connection.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values.yaml
- run.sh
- Add helm chart for deployment of ingress, service and pod
- Add dockerfile for constructing container
- Add docker-compose for running container locally 
- Alter production env config to ensure assets reference correctly
[Ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/CRM457/boards/1192?modal=detail&selectedIssue=CRM457-399)
> Add helm deploy

- app/views/landing/index.html.erb
- app/views/layouts/_primary_navigation.html.erb
1. Adds condition for not rendering the Navigation on the landing page.
2. Updates 'Start Now' link to the correct URL.
> Adds condition for not rendering navigation in landing

- app/attributes/translation_object.rb
- app/controllers/disbursements_controller.rb
- app/lib/cost_calculator.rb
- app/view_models/v1/disbursement.rb
- app/view_models/v1/work_item.rb
- app/views/adjustments/show.html.erb
- app/views/disbursements/index.html.erb
- app/views/work_items/index.html.erb
- config/locales/en/claims.yml
- config/routes.rb
- spec/controllers/disbursements_controller_spec.rb
- spec/lib/cost_calculator_spec.rb
- spec/view_models/v1/disbursement_spec.rb
- spec/view_models/v1/work_item_spec.rb
Add disbursements tab
[CRM457-429](https://dsdmoj.atlassian.net/browse/CRM457-429)
[CRM457-429]: https://dsdmoj.atlassian.net/browse/CRM457-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 429/disbursements

- app/controllers/letters_and_calls_controller.rb
- app/lib/cost_calculator.rb
- app/view_models/v1/letter_and_call.rb
- app/view_models/v1/letters_and_calls_summary.rb
- app/views/adjustments/show.html.erb
- app/views/letters_and_calls/index.html.erb
- config/locales/en/letters_and_calls.yml
- config/routes.rb
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/controllers/letters_and_calls_controller_spec.rb
- spec/lib/cost_calculator_spec.rb
- spec/view_models/v1/letter_and_call_spec.rb
- spec/view_models/v1/letters_and_calls_summary_spec.rb
[SPRINT R Caseworker: Build Review and Adjust Tab (Letter and Calls)](https://dsdmoj.atlassian.net/browse/CRM457-428)
> [CRM457-436] SPRINT R Caseworker: Build Review and Adjust Tab (Letter and Calls)

- app/controllers/make_decision_controller.rb
- app/controllers/send_back_controller.rb
- app/views/adjustments/show.html.erb
- app/views/claim_details/show.html.erb
- app/views/make_decision/index.html.erb
- app/views/send_back/index.html.erb
- app/views/shared/_claim_button_group.erb
- config/locales/en.yml
- config/locales/en/make_decision.yml
- config/locales/en/send_back.yml
- config/routes.rb
- spec/controllers/make_and_decision_controller_spec.rb
- spec/controllers/send_back_controller_spec.rb
Add buttons `Make a decision` and `Send back to provider` to `Case details` and `Review and adjust` Tab
[https://dsdmoj.atlassian.net/browse/CRM457-498](https://dsdmoj.atlassian.net/browse/CRM457-498)
> CRM457 - 498 - Add buttons "Make a decision" and "Send back to provider" (CW)

- doc/events.md
Some docs for Events
[CRM457-510](https://dsdmoj.atlassian.net/browse/CRM457-510)
[CRM457-510]: https://dsdmoj.atlassian.net/browse/CRM457-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Initial documentation for events

- app/controllers/assessed_claims_controller.rb
- app/models/claim.rb
- app/view_models/base_view_model.rb
- app/view_models/v1/assessed_claims.rb
- app/views/assessed_claims/_assessed_claims_table.html.erb
- app/views/assessed_claims/index.html.erb
- config/locales/en/assessed_claims.yml
- spec/view_models/base_view_model_spec.rb
- spec/view_models/v1/assessed_claims_spec.rb
["Assessed claims" Build landing page + interactions](https://dsdmoj.atlassian.net/browse/CRM457-483)
> [CRM457-483] "Assessed claims" Build landing page

- Dockerfile
Updating ruby image to solve High level vulnerabilities
> Updates ruby image

- app/presenters/claim_details/table.rb
- app/view_models/v1/claim_justification.rb
- app/views/adjustments/show.html.erb
- app/views/claim_details/show.html.erb
- app/views/claims/_claim_summary.html.erb
- app/views/histories/show.html.erb
- app/views/layouts/_step_header.html.erb
- app/views/layouts/govuk_template.html.erb
- app/views/shared/_claim_button_group.erb
- app/views/supporting_evidences/show.html.erb
- config/locales/en.yml
- config/locales/en/claim_details.yml
- config/locales/en/helpers.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- spec/view_models/v1/case_details_spec.rb
- spec/view_models/v1/claim_justification_spec.rb
Small fixes to the main claim and claim details sections
[CRM457-579](https://dsdmoj.atlassian.net/browse/CRM457-579)
[CRM457-579]: https://dsdmoj.atlassian.net/browse/CRM457-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 579/simple fixes

- .github/CODEOWNERS
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-dev.yaml
- Adds Service Account to app to allow access to S3 bucket
N/A
> Add service account to deployment

- app/controllers/work_items_controller.rb
- app/view_models/shared/work_item_summary.rb
- app/view_models/v1/core_cost_summary.rb
- app/view_models/v1/travel_and_waiting.rb
- app/views/claims/_claim_nav.html.erb
- app/views/work_items/index.html.erb
- config/environments/test.rb
- config/locales/en/claims.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- spec/controllers/work_items_controller_spec.rb
- spec/support/mock_trnslated.rb
- spec/view_models/v1/core_cost_summary_spec.rb
- spec/view_models/v1/travel_and_waiting_spec.rb
Add Travel and waiting summary to work items screen
[CRM457-580](https://dsdmoj.atlassian.net/browse/CRM457-580)
[CRM457-580]: https://dsdmoj.atlassian.net/browse/CRM457-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 580/travel and waiting

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/custom/history-background.scss
- app/controllers/application_controller.rb
- app/controllers/assessed_claims_controller.rb
- app/controllers/change_risks_controller.rb
- app/controllers/claims_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/make_decisions_controller.rb
- app/controllers/supporting_evidences_controller.rb
- app/controllers/your_claims_controller.rb
- app/forms/claim_note_form.rb
- app/models/event.rb
- app/models/event/note.rb
- app/views/change_risks/edit.html.erb
- app/views/histories/show.html.erb
- config/initializers/pagy.rb
- config/locales/en/change_risks.yml
- config/locales/en/claims.yml
- config/locales/en/events.yml
- config/locales/en/histories.yml
- config/routes.rb
- spec/controllers/histories_controller_spec.rb
- spec/controllers/supporting_evidences_controller_spec.rb
- spec/factories/events.rb
- spec/forms/claim_note_form_spec.rb
- spec/models/event/note_spec.rb
Allow user to add an internal claim note
Also add pagination for event history - with tidy up of includes
[CRM457-585](https://dsdmoj.atlassian.net/browse/CRM457-585)
[CRM457-585]: https://dsdmoj.atlassian.net/browse/CRM457-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 585/claim note

- app/helpers/application_helper.rb
- app/view_models/v1/case_details.rb
- app/view_models/v1/claim_details.rb
- app/view_models/v1/details_of_claim.rb
- app/view_models/v1/hearing_details.rb
- app/views/claims/_claim_summary.html.erb
- app/views/histories/show.html.erb
- app/views/shared/_pagination.html.erb
- app/views/supporting_evidences/_supporting_evidence_table.html.erb
- spec/helpers/application_helper_spec.rb
Fix timezone issue with rendered date
- also align pagination description on right
[CRM457-585](https://dsdmoj.atlassian.net/browse/CRM457-585)
[CRM457-585]: https://dsdmoj.atlassian.net/browse/CRM457-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRM457-585] Fix timezone issues with page render

- app/forms/change_risk_form.rb
- spec/forms/change_risk_form_spec.rb
[Caseworker build - Risk screen](https://dsdmoj.atlassian.net/browse/)
> [CRM457-587] Change Risk - Caseworker

- app/controllers/letters_and_calls_controller.rb
- app/forms/letters_calls_form.rb
- app/models/event/edit.rb
- app/views/letters_and_calls/edit.html.erb
- config/locales/en/letters_and_calls.yml
- spec/controllers/letters_and_calls_controller_spec.rb
- spec/factories/claims.rb
- spec/factories/versions.rb
- spec/forms/letters_calls_form_spec.rb
- spec/models/event/edit_spec.rb
Save the letter and calls adjustment
[CRM457-620](https://dsdmoj.atlassian.net/browse/CRM457-620)
As this is not fully implmenting the historic data (via events) the some feature don't work quite as expected (i.e. you can only remove uplift). This is be fixed in the next PR 
[CRM457-620]: https://dsdmoj.atlassian.net/browse/CRM457-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 620/letters calls edit part 2

- app/controllers/letters_and_calls_controller.rb
- app/forms/letters_calls_form.rb
- app/view_models/base_view_model.rb
- app/view_models/v1/core_cost_summary.rb
- app/view_models/v1/letter_and_call.rb
- app/view_models/v1/letters_and_calls_summary.rb
- app/views/letters_and_calls/edit.html.erb
- config/locales/en/letters_and_calls.yml
- spec/factories/events.rb
- spec/factories/versions.rb
- spec/view_models/base_view_model_spec.rb
- spec/view_models/v1/core_cost_summary_spec.rb
- spec/view_models/v1/letter_and_call_spec.rb
- spec/view_models/v1/letters_and_calls_summary_spec.rb
Use the events to calculate the provider requested amounts after adjustments have been made
Part 2 will focus on code quality and try to refactor and simplify how everts work/are used...
> Crm457 621/letters calls events - Part 1

- app/controllers/letters_and_calls_controller.rb
- app/forms/base_adjustment_form.rb
- app/forms/letters_calls_form.rb
- app/view_models/base_with_adjustments.rb
- app/view_models/v1/letter_and_call.rb
- app/views/letters_and_calls/edit.html.erb
- doc/adjustments.md
- spec/forms/letters_calls_form_spec.rb
Some documentation on adjustments plus some refactoring to pull base object out - will hopefully help with future PR for working items and disbursements
> [CRM457-621] - Add some document on using the events to calculate adjustements

- app/javascript/application.js
- app/javascript/component/letters_calls_adjustment.js
- app/views/letters_and_calls/edit.html.erb
- config/locales/en/letters_and_calls.yml
Added button and table for calculation after adjustment
> Added button and table for calculation

- app/view_models/base_view_model.rb
- app/view_models/v1/letter_and_call.rb
- db/migrate/20231025145658_flexible_linked_id.rb
- db/schema.rb
- spec/factories/events.rb
Refactor how adjustment events are linked
> Crm457 621/event refactor 4

- .circleci/config.yml
- helm_deploy/values-prod.yaml
Add circle ci step for deploying to production when branch is main
Add values for helm deploy for production
[Setup Caseworker App Cloud Platform Environments (PROD)](https://dsdmoj.atlassian.net/jira/software/c/projects/CRM457/boards/1192?selectedIssue=CRM457-613)
Need to merge to test
> Crm457 613 add production

- app/views/letters_and_calls/edit.html.erb
- config/locales/en/letters_and_calls.yml
> CRM457-621 - Fix bug with editing calls and translations

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/custom/moj-primary-navigation.scss
- app/views/layouts/_header_navigation.html.erb
- config/initializers/devise.rb
- config/locales/en.yml
- config/locales/en/claim_details.yml
- config/locales/en/claims.yml
- config/locales/en/histories.yml
- config/locales/en/landing.yml
- config/routes.rb
- spec/helpers/application_helper_spec.rb
- spec/system/authenticating/sign_out_spec.rb
Fix styling in the navigation headfer
[CRM457-605](https://dsdmoj.atlassian.net/browse/CRM457-605)
[CRM457-605]: https://dsdmoj.atlassian.net/browse/CRM457-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix styling issue in navigation

- lib/tasks/user.rake
> Remove auth_subject_id from update command

- app/controllers/change_risks_controller.rb
- app/views/change_risks/edit.html.erb
- app/views/your_claims/_your_claims_table.html.erb
- config/locales/en/change_risks.yml
Small bug fixes for the system
[CRM457-658](https://dsdmoj.atlassian.net/browse/CRM457-658)
[CRM457-660](https://dsdmoj.atlassian.net/browse/CRM457-660)
[CRM457-656](https://dsdmoj.atlassian.net/browse/CRM457-656)
[CRM457-658]: https://dsdmoj.atlassian.net/browse/CRM457-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRM457-660]: https://dsdmoj.atlassian.net/browse/CRM457-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRM457-656]: https://dsdmoj.atlassian.net/browse/CRM457-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change button text on chnage risk form

- app/controllers/letters_and_calls_controller.rb
- app/forms/letters_calls_form.rb
- app/view_models/v1/letter_and_call.rb
- app/view_models/v1/letters_and_calls_summary.rb
- app/views/letters_and_calls/edit.html.erb
- config/locales/en/letters_and_calls.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- lib/tasks/custom_seeds.rake
- spec/controllers/letters_and_calls_controller_spec.rb
- spec/view_models/v1/letter_and_call_spec.rb
- spec/view_models/v1/letters_and_calls_summary_spec.rb
Fix error message translations for calls
[CRM457-678](https://dsdmoj.atlassian.net/browse/CRM457-678)
[CRM457-678]: https://dsdmoj.atlassian.net/browse/CRM457-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Correct Error messages for calls

- config/sidekiq.yml
Add pooling queue to sidekiq worker
[CRM457-694](https://dsdmoj.atlassian.net/browse/CRM457-694)
[CRM457-694]: https://dsdmoj.atlassian.net/browse/CRM457-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-694 - Add pooling queue to sidekiq worker

- Gemfile.lock
- app/presenters/claim_details/table.rb
- app/view_models/v1/contact_details.rb
- app/view_models/v1/equality_details.rb
- config/locales/en/claim_details.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/view_models/v1/contact_details_spec.rb
- spec/view_models/v1/equality_details_spec.rb
Update claim details page
[CRM457-701](https://dsdmoj.atlassian.net/browse/CRM457-701)
This only shows the key values for the equality questions and will need to be updated once translations are sent from the provider app
[CRM457-701]: https://dsdmoj.atlassian.net/browse/CRM457-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 701/claim details

- Dockerfile
- Gemfile.lock
- app/javascript/component/letters_calls_adjustment.js
- app/views/letters_and_calls/edit.html.erb
Fix JS for letters and calls calculation button
[CRM457-709](https://dsdmoj.atlassian.net/browse/CRM457-709)
[CRM457-709]: https://dsdmoj.atlassian.net/browse/CRM457-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix letters and calls JS calaculation

- app/helpers/application_helper.rb
- app/models/claim.rb
- app/view_models/v1/claim_summary.rb
- app/views/claims/_claim_summary.html.erb
- app/views/letters_and_calls/index.html.erb
- app/views/shared/_claim_button_group.erb
- app/views/work_items/index.html.erb
- config/locales/en/claim_details.yml
- spec/factories/events.rb
- spec/helpers/application_helper_spec.rb
- spec/view_models/v1/claim_summary_spec.rb
Create a view only version of teh claim to use once claim has been accessed
[CRM-515](https://dsdmoj.atlassian.net/browse/CRM-515)
Split into two parts to avoid super large PR
> Crm457 515/view only - Part 1

- app/forms/work_item_form.rb
- app/helpers/application_helper.rb
- app/javascript/component/work_item_adjustment.js
- app/validators/time_period_validator.rb
- app/view_models/v1/work_item.rb
- app/views/work_items/edit.html.erb
- config/locales/en/work_items.yml
- spec/validators/time_period_validator_spec.rb
- Add extra error handling for Calculate Changes button to handle invalid inputs to time period
- Add extra validation to form in line with content design (with time_period validation)
- Code cleanup
[Work Item Edit Screen](https://dsdmoj.atlassian.net/browse/CRM457-628)
NOTE: the time_period component automatically handles non numbers by defaulting them to 0 and floats by converting them to integers so kept that behaviour in - to add explicit validation for this would mean modifications to the underlying workings of the component - if we think this should be added I can work on that
> Crm457 433 work item edit pt2

- app/services/receive_application_metadata.rb
- spec/services/receive_application_metadata_spec.rb
Remove submitted check for claims updating 
> Remove criteria for claim to not be submitted to pull version data

- app/forms/send_back_form.rb
- config/locales/en/send_back.yml
Add error messaging for send back form
[CRM457-513](https://dsdmoj.atlassian.net/browse/CRM457-513)
[CRM457-513]: https://dsdmoj.atlassian.net/browse/CRM457-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-513 -Add error messaging for send back form

- app/javascript/component/work_item_adjustment.js
- app/view_models/v1/work_item.rb
- app/views/work_items/edit.html.erb
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
Add code to handle nil values for work item uplift 
[Incorrect Uplift Value Shown in Change Work Item Form When No Uplift](https://dsdmoj.atlassian.net/browse/CRM457-741)
> Crm457 741 incorrect work item uplift

- Gemfile
- Gemfile.lock
- app/controllers/supporting_evidences_controller.rb
- app/view_models/v1/supporting_evidence.rb
- app/views/supporting_evidences/_supporting_evidence_table.html.erb
- config/initializers/aws.rb
- spec/controllers/supporting_evidences_controller_spec.rb
- spec/factories/claims.rb
- spec/system/supporting_evidence_spec.rb
- Added AWS gem and initialiser
- Updated view model for evidence
- Get presigned URL for each evidence
> CRM457-599 - Downloadable Evidence

- config/initializers/aws.rb
- Remove force_path_style as it doesnt work as a global config parameter
> CRM457-599 - Remove invalid global config param

- app/helpers/application_helper.rb
- app/models/event.rb
- app/models/event/decision.rb
- app/models/event/note.rb
- app/models/event/unassignment.rb
- app/views/histories/show.html.erb
- app/views/your_claims/_your_claims_table.html.erb
- config/locales/en/events.yml
- config/locales/en/send_back.yml
- spec/helpers/application_helper_spec.rb
- spec/models/event/assignment_spec.rb
- spec/models/event/new_version_spec.rb
- spec/models/event/note_spec.rb
- spec/models/event/send_back_spec.rb
- spec/models/event/unassignment_spec.rb
- spec/system/history_spec.rb
Ensure all events are displayed with updated copy
[CRM457-702](https://dsdmoj.atlassian.net/browse/CRM457-702)
[CRM457-702]: https://dsdmoj.atlassian.net/browse/CRM457-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 702/event history

- app/jobs/pull_updates.rb
- app/services/notify_app_store/message_builder.rb
- db/migrate/20231127112643_add_application_type.rb
- db/schema.rb
- spec/jobs/pull_updates_spec.rb
- spec/services/notify_app_store/message_builder_spec.rb
- Adds missing application_type to db schema
- Save paramater to DB so we can us this on the update call
- Update tests
> Adds application_type to claim

- Dockerfile
- app/lib/host_env.rb
- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-prod.yaml
- spec/lib/host_env_spec.rb
Standardise ENV name between provider and CW
actually use the variable to populate the value
N/A
> BUG - Standard env name variable to ENV (match provider

- app/controllers/claims_controller.rb
- app/controllers/unassignments_controller.rb
- app/forms/unassignment_form.rb
- app/models/event/unassignment.rb
- app/views/claims/_claim_summary.html.erb
- app/views/unassignments/edit.html.erb
- config/locales/en/unassignment.yml
- config/routes.rb
- spec/controllers/claims_controller_spec.rb
- spec/controllers/unassignments_controller_spec.rb
- spec/factories/assignments.rb
- spec/factories/claims.rb
- spec/forms/unassignment_form_spec.rb
- spec/models/claims_spec.rb
- spec/models/event/unassignment_spec.rb
- spec/system/history_spec.rb
Add Confirm/comment screen for removing a claim
[CRM457-732](https://dsdmoj.atlassian.net/browse/CRM457-732)
[CRM457-732]: https://dsdmoj.atlassian.net/browse/CRM457-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 732/remove claim screen

- app/controllers/change_risks_controller.rb
- app/controllers/make_decisions_controller.rb
- app/controllers/send_backs_controller.rb
- app/views/change_risks/edit.html.erb
- app/views/letters_and_calls/uplifts/edit.html.erb
- app/views/make_decisions/edit.html.erb
- app/views/send_backs/edit.html.erb
- app/views/work_items/uplifts/edit.html.erb
- spec/controllers/send_backs_controller_spec.rb
Code cleanup done as part of CRM457-732..
remove old comments]
fix back button (didn't work after form had an error)
[CRM457-732](https://dsdmoj.atlassian.net/browse/CRM457-732)
[CRM457-732]: https://dsdmoj.atlassian.net/browse/CRM457-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Code cleanup to ensure everything works as expected

- app/view_models/v1/contact_details.rb
- config/locales/en/claim_details.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/view_models/v1/contact_details_spec.rb
Show required text when no alternative contact details
[CRM457-746](https://dsdmoj.atlassian.net/browse/CRM457-746)
[CRM457-746]: https://dsdmoj.atlassian.net/browse/CRM457-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-746/no-alt-contact

- app/views/disbursements/_disbursements_total.html.erb
- config/locales/en/disbursements.yml
Change Disbursement total column headings to "Requested (including any VAT)" and "Allowed (including any VAT)"
Use calculation with VAT applied for Provider Requested value
[CRM7 Caseworkers: Adding VAT to disbursements](https://dsdmoj.atlassian.net/browse/CRM457-787)
> Update table and translations for disbursement totals

- app/javascript/component/work_item_adjustment.js
- app/lib/number_to.rb
- app/view_models/base_view_model.rb
- app/view_models/v1/work_item.rb
- app/views/work_items/edit.html.erb
- app/views/work_items/show.html.erb
- config/locales/en/work_items.yml
- spec/lib/number_to_spec.rb
- spec/view_models/v1/work_item_spec.rb
Add VAT details to work items edit/show pages
[CRM457-792](https://dsdmoj.atlassian.net/browse/CRM457-792)
[CRM457-792]: https://dsdmoj.atlassian.net/browse/CRM457-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 792/work items vat

- .gitignore
- Brewfile
Add Brewfile and .gitignore some files
The README contains instruction to brew bundle
but no Brewfile exists. This adds what appears to
be a minimal requirement of services to install
for this app.
> Add Brewfile and .gitignore some files

- .circleci/config.yml
CRM457-854: Refactor circleci config
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-854)
Dry out.
> CRM457-854: Refactor circleci config

- .github/dependabot.yml
Amend dependabot config
- add reviewer
- reduce max open PRs allowed
- group a few dependencies
> Amend dependabot config

- config/importmap.rb
Our importmap file got out of sync with our package.json
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1055)
There will be a separate ticket to assess whether we really need both an importmap and a package.json
> CRM457-1055: Update to latest MOJ-frontend

- app/views/layouts/_header_navigation.html.erb
- app/views/layouts/govuk_template.html.erb
- config/initializers/content_security_policy.rb
- Add CSP
- Make sure scripts have nonces
- Fix JS issues with header content
[CRM457-1092](https://dsdmoj.atlassian.net/browse/CRM457-1092)
[CRM457-1092]: https://dsdmoj.atlassian.net/browse/CRM457-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-1092: CSP

- Gemfile
- Gemfile.lock
- app/controllers/prior_authority/adjustments_controller.rb
- app/view_models/prior_authority/v1/additional_cost.rb
- app/view_models/prior_authority/v1/application_details/key_information_card.rb
- app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
- app/view_models/prior_authority/v1/key_information.rb
- app/view_models/prior_authority/v1/quote.rb
- app/views/prior_authority/adjustments/_additional_costs.html.erb
- app/views/prior_authority/adjustments/_key_information_card.html.erb
- app/views/prior_authority/adjustments/_service_costs.html.erb
- app/views/prior_authority/adjustments/_travel_costs.erb
- app/views/prior_authority/adjustments/index.html.erb
- app/views/prior_authority/shared/_application_nav.html.erb
- config/environments/development.rb
- config/locales/en.yml
- config/locales/en/prior_authority.yml
- config/locales/en/prior_authority/adjustments.yml
- config/locales/en/prior_authority/application_details.yml
- config/locales/en/prior_authority/applications.yml
- doc/adjustments.md
- spec/factories/prior_authority_applications.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/view_models/prior_authority/v1/additional_cost_spec.rb
- spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
- spec/view_models/prior_authority/v1/key_information_spec.rb
- spec/view_models/prior_authority/v1/quote_spec.rb
Add quote adjustment elements
[relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1115)
- add key information card
- add service cost section
- add travel cost section
- add additional cost sections
> CRM457 1115: Add quote adjustment tab

- app/javascript/component/letters_calls_adjustment.js
- app/javascript/component/work_item_adjustment.js
- config/locales/en/nsm/disbursements.yml
Some JS was broken when we namespaced NSM. Plus there's a missing translation.
> Get NSM JS working again

- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-uat.yaml
- Change nsm-elasticache to crm-elasticache 
[Setup New Kubernetes Namespaces for Caseworker App](https://dsdmoj.atlassian.net/browse/CRM457-941)
> Fix Reference to Incorrect Elasticache Secret

- app/view_models/prior_authority/v1/additional_cost.rb
- app/view_models/prior_authority/v1/application_details.rb
- app/view_models/prior_authority/v1/application_details/case_details_card.rb
- app/view_models/prior_authority/v1/application_summary.rb
- app/view_models/prior_authority/v1/key_information.rb
- app/view_models/prior_authority/v1/quote.rb
- app/views/prior_authority/applications/_primary_quote_card.html.erb
- app/views/prior_authority/applications/show.html.erb
- config/locales/en/prior_authority/application_details.yml
- config/locales/en/prior_authority/offences.yml
- config/locales/en/prior_authority/prisons.yml
- db/migrate/20240307154917_update_data_blobs.rb
- db/schema.rb
- spec/factories/prior_authority_applications.rb
- spec/system/accessibility_spec.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/system/prior_authority/view_applications_spec.rb
- spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
- spec/view_models/prior_authority/v1/application_details_spec.rb
- spec/view_models/prior_authority/v1/application_summary_spec.rb
- spec/view_models/prior_authority/v1/key_information_spec.rb
- spec/view_models/prior_authority/v1/quote_spec.rb
- Accommodate main_offence_id and prison_id fields
- Tweak view application to match designs
- Accommodate "page"/"minute"/"word" item types
- Better tests
[CRM457-1041](https://dsdmoj.atlassian.net/browse/CRM457-1041)
[CRM457-1041]: https://dsdmoj.atlassian.net/browse/CRM457-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-1041: Offence and prison lists

- app/forms/prior_authority/additional_cost_form.rb
- app/forms/prior_authority/base_cost_adjustment_form.rb
- app/forms/prior_authority/service_cost_form.rb
- app/javascript/application.js
- app/javascript/component/prior_authority/additional_cost_adjustment.js
- app/javascript/component/prior_authority/cost_adjustment.js
- app/javascript/component/prior_authority/service_cost_adjustment.js
- app/view_models/prior_authority/additional_costs_with_adjustments.rb
- app/view_models/prior_authority/v1/additional_cost.rb
- app/view_models/prior_authority/v1/quote.rb
- app/views/prior_authority/additional_costs/_cost_fields.html.erb
- app/views/prior_authority/additional_costs/edit.html.erb
- app/views/prior_authority/adjustments/_additional_costs.html.erb
- config/locales/en/prior_authority/additional_costs.yml
- spec/system/prior_authority/adjust_additional_costs_spec.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/view_models/prior_authority/v1/additional_cost_spec.rb
Add additional costs form
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-1114)
Alongside the servce costs form and travel costs forms
this is the final work, for now, on Adjustment forms.
- add form and get it working
- add javascript for updating on the page
> CRM457-1114: Add additional costs form

- .github/pull_request_template.md
Amend PR template
Makes it simpler/quicker to add the ticket reference, and in line
with submit  PR template.
> Amend PR template

- app/controllers/prior_authority/applications_controller.rb
- app/controllers/prior_authority/assignments_controller.rb
- app/controllers/prior_authority/auto_assignments_controller.rb
- app/controllers/prior_authority/manual_assignments_controller.rb
- app/controllers/prior_authority/unassignments_controller.rb
- app/forms/prior_authority/manual_assignment_form.rb
- app/forms/prior_authority/unassignment_form.rb
- app/helpers/sortable_table_helper.rb
- app/models/event/assignment.rb
- app/services/prior_authority/sorter.rb
- app/view_models/prior_authority/v1/application_summary.rb
- app/view_models/prior_authority/v1/table_row.rb
- app/views/prior_authority/applications/your.html.erb
- app/views/prior_authority/manual_assignments/new.html.erb
- app/views/prior_authority/shared/_application_nav.html.erb
- app/views/prior_authority/unassignments/new.html.erb
- app/views/shared/_pagination.html.erb
- app/views/shared/_pagination_info.html.erb
- config/locales/en/prior_authority.yml
- config/locales/en/prior_authority/manual_assignments.yml
- config/locales/en/prior_authority/unassignments.yml
- config/routes.rb
- spec/system/prior_authority/adjust_additional_costs_spec.rb
- spec/system/prior_authority/adjust_service_costs_spec.rb
- spec/system/prior_authority/adjust_travel_costs_spec.rb
- spec/system/prior_authority/adjustments_spec.rb
- spec/system/prior_authority/application_lists_spec.rb
- spec/system/prior_authority/assign_applications_spec.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
Manually assign unassigned applications to yourself
Unassign assigned applications from any caseworker
[CRM457-997](https://dsdmoj.atlassian.net/browse/CRM457-997)
[CRM457-997]: https://dsdmoj.atlassian.net/browse/CRM457-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-997: Manual assignment and unassignment

- helm_deploy/values-uat.yaml
Fix reference to appStoreUrl
check if sidekiq worker does not encounter this after merge
```
Errno::ECONNREFUSED: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
```
> rename var to expected name

- config/locales/en/errors.yml
> remove space

- app/views/prior_authority/related_applications/index.html.erb
- spec/system/prior_authority/view_related_applications_spec.rb
Related applications QA changes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-993)
- Fix reference to summary id, and tests that exercise that page
- Remove h2 for no application text
> CRM457-993: QA changes

- app/models/event.rb
- app/models/prior_authority_application.rb
- spec/jobs/pull_latest_version_data_spec.rb
Fix bug with access table not being visible in branch environments due to missing data - caused by invalid events
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1240)
> Crm457 1240/event users

- .rubocop.yml
- app/models/event.rb
- app/models/prior_authority_application.rb
- app/view_models/nsm/v1/work_item.rb
- lib/govuk_design_system_formbuilder/elements/period.rb
- spec/jobs/pull_latest_version_data_spec.rb
Fix missing code from last merge
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1240)
> Crm457 1240/event users fix

- helm_deploy/values-dev.yaml
With linking to certificate
[Custom Domain Names - Caseworker Dev](https://dsdmoj.atlassian.net/jira/software/c/projects/CRM457/boards/1192?selectedIssue=CRM457-864)
Note: this is just for dev as I want to test one before I do the others
> Change domain to new custom domain

- app/controllers/prior_authority/applications_controller.rb
- app/controllers/prior_authority/related_applications_controller.rb
- app/models/prior_authority_application.rb
- app/services/prior_authority/sorter.rb
- app/view_models/prior_authority/v1/table_row.rb
- app/views/layouts/prior_authority/_primary_navigation.html.erb
- app/views/prior_authority/applications/closed.html.erb
- app/views/prior_authority/applications/open.html.erb
- app/views/prior_authority/applications/your.html.erb
- config/locales/en/prior_authority.yml
- config/locales/en/prior_authority/applications.yml
- config/routes.rb
- spec/system/prior_authority/application_lists_spec.rb
- spec/system/prior_authority/view_related_applications_spec.rb
Adjust UI to accommodate expired applications, which largely involves standardising tables.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1195)
> CRM457-1195: Adjust expired application UI

- app/controllers/prior_authority/applications_controller.rb
- app/controllers/prior_authority/related_applications_controller.rb
- app/helpers/prior_authority_tag_helper.rb
- app/jobs/expire_sendbacks.rb
- app/models/event.rb
- app/models/event/expiry.rb
- app/models/prior_authority_application.rb
- app/services/notify_app_store.rb
- app/services/prior_authority/sorter.rb
- app/view_models/prior_authority/v1/application_summary.rb
- app/view_models/prior_authority/v1/event_summary.rb
- app/view_models/prior_authority/v1/table_row.rb
- app/views/layouts/prior_authority/_primary_navigation.html.erb
- app/views/prior_authority/applications/closed.html.erb
- app/views/prior_authority/applications/open.html.erb
- app/views/prior_authority/applications/show.html.erb
- app/views/prior_authority/applications/your.html.erb
- app/views/prior_authority/shared/_application_nav.html.erb
- config/locales/en/prior_authority.yml
- config/locales/en/prior_authority/applications.yml
- config/locales/en/prior_authority/events.yml
- config/routes.rb
- config/schedule.yml
- spec/jobs/expire_sendbacks_spec.rb
- spec/services/notify_app_store_spec.rb
- spec/system/prior_authority/application_lists_spec.rb
- spec/system/prior_authority/view_related_applications_spec.rb
- Set a schedule
- Add logic to update state, create an event, then send back to app store
- Make sure expired applications show up in the right places without breaking anything (there's a separate ticket for fine details of UI
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1195)
> CRM457-1195: Expire old send-backs

- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
[Custom domains](https://dsdmoj.atlassian.net/browse/CRM457-864)
> Update domains for UAT and Prod

- app/views/nsm/adjustments/show.html.erb
- app/views/nsm/claim_details/show.html.erb
- app/views/nsm/histories/show.html.erb
- app/views/nsm/supporting_evidences/show.html.erb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1273)
> CRM457-1273: Make layout more consistent and avoid rows inside columns

- config/environments/production.rb
- helm_deploy/templates/deployment.yaml
Ensure that we only authorize requests via specific named hosts
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1285)
> CRM457-1285: Host whitelisting

- app/models/event.rb
Fix record not unique error with locking: https://ministryofjustice.sentry.io/issues/5140993258/?referrer=slack&notification_uuid=b5f82687-a24c-4514-8a78-6dcb729b68c5&alert_rule_id=14899609&alert_type=issue
Fix foreign key error by making sure we have secondary users in the DB: https://ministryofjustice.sentry.io/issues/5140963387/?referrer=slack&notification_uuid=edfaf83b-80a9-4dba-bae7-37aebc1edac9&alert_rule_id=14899609&alert_type=issue
> Bug fix dummy user creation

- app/view_models/prior_authority/v1/application_details/base_card.rb
- app/view_models/prior_authority/v1/application_details/case_contact_card.rb
- app/view_models/prior_authority/v1/quote.rb
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/factories/claims.rb
- spec/factories/prior_authority_applications.rb
- spec/view_models/nsm/v1/contact_details_spec.rb
- spec/view_models/prior_authority/v1/application_details_spec.rb
Get ready for updated format of contact names
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1181)
> CRM457-1181: Separate name fields

- app/controllers/robots_controller.rb
- app/views/layouts/govuk_template.html.erb
- app/views/robots/allow.text
- app/views/robots/disallow.text
- config/routes.rb
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
- public/robots.txt
- spec/requests/robots_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-887)
> CRM457-887: Request Google not to index non-production environments

- app/models/event.rb
We're still seeing errors where a user with a given ID isn't found, so we try to create it, only to find it's already there. I _think_ it's due to our locking not working because it's not interacting with transactions properly, and I have what may be a fix.
> Try to get locking working reliably

- app/forms/prior_authority/decision_form.rb
- config/locales/en/prior_authority/decisions.yml
- spec/forms/prior_authority/decision_form_spec.rb
- spec/system/prior_authority/make_decision_spec.rb
Add more validations on assess PA
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1236)
> CRM457-1236: Prevent rejecting or granting if adjustments have been made

- app/views/nsm/supporting_evidences/show.html.erb
- config/feature_flags.yml
- spec/system/nsm/supporting_evidence_spec.rb
Feature flag postal evidence content
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1308)
> CRM457-1308: Postal evidence

- app/view_models/prior_authority/v1/application_details/alternative_quote_card.rb
- app/view_models/prior_authority/v1/application_details/base_card.rb
- app/view_models/prior_authority/v1/application_details/hearing_details_card.rb
- app/view_models/prior_authority/v1/application_details/no_alternative_quotes_card.rb
- app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
- app/view_models/prior_authority/v1/application_details/reason_why_card.rb
- app/views/prior_authority/adjustments/_additional_costs.html.erb
- app/views/prior_authority/adjustments/_travel_costs.erb
- config/locales/en/prior_authority/adjustments.yml
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/system/prior_authority/view_applications_spec.rb
- spec/view_models/prior_authority/v1/application_details_spec.rb
Use simple_format throughout
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1172)
> CRM457-1172: Add line breaks to multi-line text

- app/mailers/nsm/feedback_messages/feedback_base.rb
- app/mailers/nsm/feedback_messages/part_granted_feedback.rb
- app/models/claim.rb
- app/view_models/nsm/v1/claim_summary.rb
- app/view_models/nsm/v1/core_cost_summary.rb
- app/views/nsm/claims/_claim_summary.html.erb
- config/locales/en/nsm/claims.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
- spec/mailers/nsm/feedback_messages/granted_feedback_spec.rb
- spec/mailers/nsm/feedback_messages/part_granted_feedback_spec.rb
- spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb
- spec/mailers/nsm/feedback_messages/rejected_feedback_spec.rb
- spec/mailers/nsm/submission_feedback_mailer_spec.rb
- spec/system/nsm/overview_spec.rb
- spec/view_models/nsm/v1/claim_summary_spec.rb
- spec/view_models/nsm/v1/core_cost_summary_spec.rb
Add "Claimed" "Allowed" totals to the top of NSM claims
Also fix some bugs - explanations in comments.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-762)
> CRM457-762: Show totals at top (and bug-fixes)

- app/view_models/nsm/v1/all_claims.rb
- app/view_models/nsm/v1/assessed_claims.rb
- app/view_models/nsm/v1/your_claims.rb
- spec/view_models/nsm/v1/all_claims_spec.rb
- spec/view_models/nsm/v1/assessed_claims_spec.rb
- spec/view_models/nsm/v1/your_claims_spec.rb
Use the local timestamps, not timestamps in the payload from the provider app.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1365)
> CRM457-1365: Wrong timestamps

- .circleci/config.yml
Add e2e tests to pipeline
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1301)
So that we can test changes against full flow through app
> CRM457-917: Add circleci config for e2e tests

- app/controllers/nsm/assessed_claims_controller.rb
- app/controllers/nsm/claims_controller.rb
Otherwise when there are 100,000 items in the database, you load them _all_ just to render 10...
> Paginate before mapping

- helm_deploy/values-dev.yaml
> Update app store url

- app/views/prior_authority/related_applications/_table.html.erb
- app/views/prior_authority/related_applications/index.html.erb
- config/locales/en/prior_authority/related_applications.yml
Add target _blank
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1375)
> CRM457-1375: Open related applications in new tabs

- app/controllers/prior_authority/notes_controller.rb
- app/forms/prior_authority/note_form.rb
- app/view_models/prior_authority/v1/event_summary.rb
- app/views/prior_authority/events/index.html.erb
- app/views/prior_authority/notes/new.html.erb
- config/locales/en/errors.yml
- config/locales/en/prior_authority/events.yml
- config/locales/en/prior_authority/notes.yml
- config/routes.rb
- spec/factories/events.rb
- spec/system/prior_authority/history_spec.rb
- spec/system/prior_authority/notes_spec.rb
- spec/view_models/prior_authority/v1/event_summary_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1326)
> CRM457-1326: Add notes to PA applications

- app/view_models/prior_authority/v1/application_details/key_information_card.rb
- app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
- app/view_models/prior_authority/v1/quote.rb
- config/locales/en/prior_authority/application_details.yml
- spec/factories/prior_authority_applications.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/system/prior_authority/view_applications_spec.rb
- spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
- spec/view_models/prior_authority/v1/application_details_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1313)
> CRM457-1313: View town

- app/controllers/about/privacy_controller.rb
- app/views/about/privacy/index.en.html.erb
- app/views/layouts/_footer_links.html.erb
- config/routes.rb
- spec/system/privacy_policy_spec.rb
Add privacy policy view, controller and link
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1069)
Do we want to test this? I have added a basic system test but 🤷
> CRM457-1069: Add privacy policy view, controller and link

- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
Increase prod and UAT replicaCount
[Relates to/came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-1455)
This value is only used when autoscaling is disabled and should
match the minReplica number specified for autoscaling for
consistency.
> CRM457-1455: Increase prod and UAT replicaCount

- config/feature_flags.yml
> Allow dev login in UAT

- app/views/about/privacy/index.en.html.erb
Amendments to privacy policy content
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1069)
Amendments from content designer
> CRM457-1069: Amendments to privacy policy content

- app/lib/number_to.rb
- app/view_models/nsm/v1/letter_and_call.rb
- app/view_models/nsm/v1/work_item.rb
- app/views/nsm/letters_and_calls/edit.html.erb
- app/views/nsm/work_items/edit.html.erb
- spec/view_models/nsm/v1/letter_and_call_spec.rb
- spec/view_models/nsm/v1/work_item_spec.rb
Stop rounding down
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-850)
> CRM457-850: Stop rounding down

- config/locales/en.yml
- config/locales/en/nsm/assessed_claims.yml
- config/locales/en/nsm/claims.yml
Switch to open/closed nomenclature
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1322)
> CRM457-1322: Update page names

- app/view_models/nsm/v1/your_claims.rb
- app/views/nsm/your_claims/_your_claims_table.html.erb
- config/locales/en/nsm/your_claims.yml
- spec/view_models/nsm/v1/your_claims_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1461)
> CRM457-1461: Show in-progress tags on "your claims" page

- app/views/nsm/your_claims/index.html.erb
- config/locales/en/nsm/your_claims.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1451)
> CRM457-1451: Remove check all claims link

- app/attributes/integer_time_period.rb
- app/javascript/component/nsm/letters_calls_adjustment.js
- app/javascript/component/nsm/work_item_adjustment.js
- app/javascript/component/prior_authority/cost_adjustment.js
- app/javascript/component/prior_authority/travel_cost_adjustment.js
- app/view_models/nsm/v1/letter_and_call.rb
- app/view_models/nsm/v1/work_item.rb
- package.json
- spec/attributes/integer_time_period_spec.rb
- spec/view_models/nsm/v1/work_item_spec.rb
- yarn.lock
We were explicitly casting some values as floats, and IntegerTimePeriod multiplications were being quietly converted to floats even when multiplied with decimals. This was leading to rounding errors.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1467)
> CRM457-1467: Fix floating point rounding errors

- helm_deploy/values-dev.yaml
> Modsec change to allow big data chunck

- app/controllers/nsm/claims_controller.rb
- spec/system/nsm/assignment_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1527)
> CRM457-1527: Prefer older claims

- app/controllers/about/accessibility_controller.rb
- app/views/about/accessibility/index.en.html.erb
- app/views/layouts/_footer_links.html.erb
- config/routes.rb
- spec/system/accessibility_statement_spec.rb
Add accessibility statement page
[Relates to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1363)
No content available yet
> Add accessibility statement page

- app/controllers/prior_authority/service_costs_controller.rb
- app/forms/prior_authority/base_cost_adjustment_form.rb
- app/forms/prior_authority/service_cost_form.rb
- app/javascript/component/prior_authority/additional_cost_adjustment.js
- app/javascript/component/prior_authority/cost_adjustment.js
- app/javascript/component/prior_authority/service_cost_adjustment.js
- app/validators/cost_item_type_dependant_validator.rb
- app/view_models/prior_authority/service_costs_with_adjustments.rb
- app/view_models/prior_authority/v1/quote.rb
- app/view_models/prior_authority/v1/service_cost.rb
- app/views/prior_authority/service_costs/_cost_fields.html.erb
- app/views/prior_authority/service_costs/edit.html.erb
- config/locales/en/prior_authority/application_details.yml
- config/locales/en/prior_authority/service_costs.yml
- spec/factories/prior_authority_applications.rb
- spec/system/prior_authority/adjust_service_costs_spec.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/validators/cost_item_type_dependant_validator_spec.rb
- spec/view_models/prior_authority/v1/quote_spec.rb
[CRM4 - Content/Calculation Change - Service Type - Translation (documents)](https://dsdmoj.atlassian.net/browse/CRM457-1612)
- Update quote view model to consume extra fields from provider app (cost_multiplier, cost_item_type)
- Update service costs with adjustments model view to consume and use cost multiplier
- Update views that include service cost (cost fields, service costs)
- Update CostAdjustment javascript to multiply item totals by cost multiplier (unless additional cost)
- Update tests
> CRM4 - Content/Calculation Change - Service Type - Translation (documents)

- app/mailers/nsm/feedback_messages/feedback_base.rb
- spec/mailers/nsm/feedback_messages/feedback_base_spec.rb
Prefer alternative contact email if provided
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1618)
> CRM457-1618: Send to correct email

- config/locales/en/nsm/send_back.yml
- spec/controllers/nsm/send_backs_controller_spec.rb
'You send' should be 'You sent'
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1622)
> CRM457-1622: Fix typo

- config/locales/en/assess_a_crime_form.yml
- spec/system/nsm/disbursements_spec.rb
- spec/system/nsm/letters_and_calls_spec.rb
- spec/system/nsm/work_items_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1580)
> CRM457-1580: Switch service becomes Change service

- .github/pull_request_template.md
> Remove unneccessary space

- app/controllers/dashboards_controller.rb
- app/views/layouts/_header_navigation.html.erb
- config/feature_flags.yml
- config/routes.rb
- spec/system/dashboards_spec.rb
[Feature flag for insights](https://dsdmoj.atlassian.net/browse/CRM457-1634)
> Add feature flag for insights

- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
[Add TLS cert and custom domain for metabase deployments in app store](https://dsdmoj.atlassian.net/browse/CRM457-1546)
> Update Metabase URLs to custom domains

- helm_deploy/templates/deployment.yaml
- helm_deploy/templates/service.yaml
> Try to specify web pods

- spec/view_models/nsm/v1/disbursement_spec.rb
Tweak spec example description
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1652)
Copy paste typo
> CRM457-1652: Tweak spec example description

- helm_deploy/templates/custom-error-pages.yaml
> Config-disable custom-errors configmap

- .github/actions/delete-dev-release/action.yml
Delete redis pvc on merge into main
We have 215 of these currently. This will help to tidy up on branch close going forward.
> Delete redis pvc on merge into main

- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- spec/factories/claims.rb
- spec/view_models/nsm/v1/claim_justification_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1675)
> CRM457-1675: Fix spelling mistake

- app/forms/nsm/work_item_form.rb
- config/locales/en/nsm/work_items.yml
Allow zero for work item time periods
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1674)
> CRM457-1674: Fix time period config

- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
Missed bits from previous related PRs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM45-1360)
> CRM457-1360: Sidekiq metrics tweaks

- Gemfile.lock
Update gemfile lock file for apple silicon M1 machines
Keeps generating diff on my machine, at least?!
> Update gemfile lock file for apple silicon M1 machines

- .circleci/config.yml
Alert to Slack on CI failures
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1579)
> CRM457-1579: Notify via Slack on failure

- Gemfile.lock
- app/views/about/accessibility/index.en.html.erb
Add accessibility statement
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1655)
> CRM457-1655: Accessibility content

- Gemfile.lock
- app/view_models/prior_authority/v1/additional_cost.rb
- app/views/prior_authority/adjustments/_additional_costs.html.erb
- app/views/prior_authority/applications/_primary_quote_card.html.erb
- config/locales/en/prior_authority/additional_costs.yml
- config/locales/en/prior_authority/adjustments.yml
- config/locales/en/prior_authority/application_details.yml
- config/locales/en/prior_authority/applications.yml
- config/locales/en/prior_authority/service_costs.yml
- config/locales/en/prior_authority/travel_costs.yml
- spec/system/prior_authority/adjust_additional_costs_spec.rb
- spec/system/prior_authority/adjust_service_costs_spec.rb
- spec/system/prior_authority/adjust_travel_costs_spec.rb
- spec/system/prior_authority/adjustments_spec.rb
- spec/system/prior_authority/delete_adjustments_spec.rb
- spec/system/prior_authority/view_adjust_quote_spec.rb
- spec/system/prior_authority/view_applications_spec.rb
- spec/view_models/prior_authority/v1/additional_cost_spec.rb
Adjust labels to standardise
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1637)
> CRM457-1637: Change labels to make more consistent

- app/controllers/nsm/downloads_controller.rb
- app/controllers/prior_authority/downloads_controller.rb
- spec/system/feedback_spec.rb
- spec/system/prior_authority/view_applications_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1691)
> CRM457-1691: Handle filenames with commas

- .circleci/config.yml
Start build-to-ecr immediately
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1658)
> [CRM457-1658] Start build-to-ecr immediately

- app/controllers/dashboards_controller.rb
- app/views/dashboards/_autogrant.html.erb
- app/views/dashboards/_dashboard_iframe.html.erb
- app/views/dashboards/_prior_authority_nav.html.erb
- app/views/dashboards/_tab_content.html.erb
- config/feature_flags.yml
- config/locales/en/dashboards.yml
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
- spec/controllers/dashboard_controller_spec.rb
- spec/system/dashboards_spec.rb
[Provider: Analytics Dashboard Tab (CRM4 & CRM7)](https://dsdmoj.atlassian.net/browse/CRM457-1636)
> Provider: Analytics Dashboard Tab (CRM4 & CRM7)

- app/view_models/nsm/v1/claim_summary.rb
- app/views/nsm/claim_details/show.html.erb
- config/locales/en/nsm/claim_details.yml
- spec/system/nsm/assessment_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1678)
> CRM457-1678: Show comment on overview page for assessed claims

- app/views/shared/_claim_button_group.erb
- config/locales/en.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1754)
Also fix a typo
> CRM457-1754: Fix button styling

- .env.test
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/custom/search.scss
- app/controllers/prior_authority/searches_controller.rb
- app/forms/search.rb
- app/forms/search_form.rb
- app/helpers/sortable_table_helper.rb
- app/models/search_result.rb
- app/services/app_store_client.rb
- app/services/update_submission.rb
- app/view_models/search_result.rb
- app/views/layouts/prior_authority/_primary_navigation.html.erb
- app/views/nsm/claims/_table.html.erb
- app/views/prior_authority/applications/_table.html.erb
- app/views/prior_authority/related_applications/_table.html.erb
- app/views/prior_authority/searches/show.html.erb
- config/feature_flags.yml
- config/locales/en/prior_authority.yml
- config/locales/en/prior_authority/search.yml
- config/routes.rb
- spec/services/app_store_client_spec.rb
- spec/system/prior_authority/search_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1557)
... Wait for a back-end or hack the AppStoreClient to return a payload similar to the specs.
> CRM457-1557: Add search UI

- app/controllers/nsm/work_items_controller.rb
- app/helpers/application_helper.rb
- app/helpers/sortable_table_helper.rb
- app/services/sorters/work_items_sorter.rb
- app/view_models/nsm/v1/core_cost_summary.rb
- app/view_models/nsm/v1/work_item.rb
- app/view_models/nsm/v1/work_item_summary.rb
- app/views/nsm/adjustments/show.html.erb
- app/views/nsm/work_items/index.html.erb
- config/locales/en/helpers.yml
- config/locales/en/nsm/claims.yml
- config/locales/en/nsm/work_items.yml
- spec/controllers/nsm/work_items_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/services/sorters/work_items_sorter_spec.rb
- spec/system/nsm/work_items_spec.rb
- spec/view_models/nsm/v1/core_cost_summary_spec.rb
- spec/view_models/nsm/v1/work_item_spec.rb
- spec/view_models/nsm/v1/work_items_summary_spec.rb
Update review and adjustsceen based off updated designs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1723)
> Crm457 1723/updated crm7

- app/views/nsm/disbursements/_adjusted.html.erb
remove incorrect style
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1737)
> [CRM457-1737] remove incorrect no-wrap style

- app/views/nsm/adjustments/show.html.erb
- app/views/nsm/review_and_adjusts/show.html.erb
Fix position of review and adjustments headers
this was broken in the previous refactpring
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1737)
> Move header back to correct position

- app/views/nsm/claim_details/show.html.erb
- config/locales/en/nsm/disbursements.yml
- spec/factories/events.rb
- spec/system/nsm/overview_spec.rb
Fix broken link and add regression for page generally
The route was removed in https://github.com/ministryofjustice/laa-assess-crime-forms/pull/638
> Amend broken link

- .circleci/config.yml
- package.json
- yarn.lock
Suggestion made by Joel [in another PR](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1033#pullrequestreview-2211823418)
> CRM457-1547: Only attempt to install yamllint and helm_client once in linting step

- helm_deploy/values-uat.yaml
During pen testing we turned modsec off in UAT. This turns it back on
> Turn modsec back on in uat

- app/forms/nsm/send_back_form.rb
- app/helpers/submission_tag_helper.rb
- app/models/claim.rb
- app/models/nsm/event/send_back.rb
- app/services/sorter.rb
- config/locales/en.yml
- config/locales/en/events.yml
- config/locales/en/nsm/your_claims.yml
- db/migrate/20240808115142_update_status.rb
- db/schema.rb
- spec/controllers/nsm/unassignments_controller_spec.rb
- spec/forms/nsm/send_back_form_spec.rb
- spec/jobs/nsm/fake_assess_spec.rb
- spec/mailers/nsm/submission_feedback_mailer_spec.rb
- spec/models/event/send_back_spec.rb
- spec/system/nsm/history_spec.rb
- spec/system/nsm/view_claims_table_spec.rb
Merge alongside matching PRs in other repos
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1784)
> CRM457-1784: New sent back status

- app/forms/search_form.rb
- config/locales/en/prior_authority/search.yml
- spec/system/dashboards_spec.rb
[CRM 4 & 7: Metabase pages](https://dsdmoj.atlassian.net/browse/CRM457-1577)
- This is an extra PR to address [this QA comment](https://dsdmoj.atlassian.net/browse/CRM457-1577?focusedCommentId=490733)
> CRM457-1577: Add check for application_type if it's an option

- app/view_models/nsm/v1/details_of_claim.rb
- app/view_models/nsm/v1/hearing_details.rb
- config/locales/en/nsm/claim_details.yml
- db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
- db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
- spec/factories/claims.rb
- spec/view_models/nsm/v1/details_of_claim_spec.rb
- spec/view_models/nsm/v1/hearing_details_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1836)
> CRM457-1836: Show prom/prog and BOI details

- app/forms/nsm/make_decision_form.rb
- app/forms/nsm/send_back_form.rb
- app/forms/prior_authority/decision_form.rb
- db/migrate/20240809091311_backfill_assessment_comments.rb
- db/schema.rb
- spec/forms/nsm/make_decision_form_spec.rb
- spec/forms/nsm/send_back_form_spec.rb
- spec/forms/prior_authority/decision_form_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1785)
> CRM457-1785: Add assessment comment to payload

- config/locales/en/prior_authority/application_details.yml
- spec/view_models/prior_authority/v1/application_details_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1788)
> CRM457-1788: Change maat naming

- .rubocop.yml
- app/attributes/type/translated_object.rb
- app/controllers/nsm/work_items_controller.rb
- app/forms/nsm/work_item_form.rb
- app/javascript/component/nsm/work_item_adjustment.js
- app/jobs/nsm/fake_assess.rb
- app/view_models/nsm/v1/work_item.rb
- app/view_models/nsm/v1/work_item_summary.rb
- app/views/nsm/work_items/_adjusted.html.erb
- app/views/nsm/work_items/_index.html.erb
- app/views/nsm/work_items/edit.html.erb
- app/views/nsm/work_items/show.html.erb
- config/locales/en/nsm/work_items.yml
- spec/controllers/nsm/work_items_controller_spec.rb
- spec/factories/claims.rb
- spec/forms/nsm/disbursements_form_spec.rb
- spec/forms/nsm/work_item_form_spec.rb
- spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
- spec/system/nsm/work_items_spec.rb
- spec/view_models/nsm/v1/work_item_spec.rb
Allow caseworkers to change work type If this change is made, display the new work type in the list view, use the correct pricing for the work item, and show hints that work type has changed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1689)
> CRM457-1689: Allow changing work type

- app/controllers/nsm/claims_controller.rb
- app/views/nsm/claims/your.html.erb
- config/locales/en/nsm/claims.yml
- config/routes.rb
- spec/controllers/nsm/claims_controller_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1900)
> CRM457-1900: CRM7 caseworker: Hovering over 'Assess next claim' button assigns a claim to you

- db/migrate/20240819153853_backfill_work_item_position.rb
- db/schema.rb
- lib/data_migration_tools/work_item_position_updater.rb
- spec/factories/work_items.rb
- spec/lib/data_migration_tools/work_item_position_updater_spec.rb
Backfill work item position
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
Inline with other backfilling. This is only required for DEV main and
UAT currently as not data exists on prod for NSM claims.
> CRM457-1812: Backfill work item position

- config/feature_flags.yml
> UAT maintenance mode for db upgrade

- config/feature_flags.yml
Reverts ministryofjustice/laa-assess-crime-forms#703
> Revert "UAT maintenance mode for db upgrade"

- config/initializers/aws.rb
Startup time improvement since we don't always need to check for AWS
[Related discussion](https://mojdt.slack.com/archives/C05212WRK5J/p1724164271099309)
> Don't initialize AWS if not needed

- app/view_models/nsm/v1/contact_details.rb
- config/locales/en/nsm/claim_details.yml
- spec/view_models/nsm/v1/contact_details_spec.rb
Contact details are now mandatory, not treated as 'alternate'
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1867)
> CRM457-1867: Update wording of contact details

- app/forms/nsm/make_decision_form.rb
- app/forms/nsm/send_back_form.rb
- app/forms/prior_authority/send_back_form.rb
- app/jobs/expire_sendbacks.rb
- app/jobs/nsm/fake_assess.rb
- app/models/claim.rb
- app/views/nsm/make_decisions/edit.html.erb
- app/views/prior_authority/applications/show.html.erb
- app/views/prior_authority/shared/_application_nav.html.erb
- lib/tasks/dummy_assessments.rake
- spec/mailers/nsm/submission_feedback_mailer_spec.rb
- spec/models/claims_spec.rb
- spec/models/event/auto_decision_spec.rb
- spec/services/update_submission_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1803)
> CRM457-1803: Add claim state enum and use enums more

- app/models/claim.rb
- app/view_models/nsm/v1/claim_summary.rb
- app/view_models/nsm/v1/disbursement.rb
- app/views/nsm/claims/_claim_summary.html.erb
- config/locales/en/nsm/claims.yml
- spec/system/nsm/assessment_spec.rb
- spec/system/nsm/disbursements_spec.rb
- spec/view_models/nsm/v1/disbursement_spec.rb
Show right dates in right format
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1644)
> CRM457-1644: Claim dates

- app/view_models/nsm/v1/contact_details.rb
- app/view_models/nsm/v1/details_of_claim.rb
- config/locales/en/nsm/claim_details.yml
- spec/view_models/nsm/v1/contact_details_spec.rb
- spec/view_models/nsm/v1/details_of_claim_spec.rb
Move office code question to a different card
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1861)
> CRM457-1861: Move office code question

- app/views/nsm/letters_and_calls/_adjusted.html.erb
Double header for adjusted letters and calls.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1846)
> CRM457-1846: Remove redundant header

- .rubocop.yml
- app/helpers/application_helper.rb
Also excluded some big folders from rubocop which can significantly speed it up.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1935)
> CRM457-1935: Sent back claims show with 'Closed' nav tab highlighted

- app/view_models/nsm/v1/defendant_details.rb
- spec/view_models/nsm/v1/defendant_details_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1922)
> CRM457-1922: Only show maat if it is provided

- config/feature_flags.yml
Enable maintenance mode on **PROD**
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1907)
For database upgrade.
> CMR457-1907: Enable maintenance mode on production

- config/feature_flags.yml
Reverts ministryofjustice/laa-assess-crime-forms#727
> Revert "CMR457-1907: Enable maintenance mode on production"

- app/views/nsm/letters_and_calls/_index.html.erb
- config/locales/en/nsm/letters_and_calls.yml
Always show letters and calls table to allow adding items
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1956)
> CRM457-1956: Allow adding letters and calls when originally zero

- app/views/nsm/adjustments/show.html.erb
- app/views/nsm/review_and_adjusts/show.html.erb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1958)
> CRM457-1958: Tab clicks should link to the tab bar

- app/view_models/nsm/v1/work_item.rb
- app/views/nsm/disbursements/show.html.erb
- app/views/nsm/letters_and_calls/show.html.erb
- app/views/nsm/work_items/edit.html.erb
- app/views/nsm/work_items/show.html.erb
- config/locales/en/nsm/disbursements.yml
- config/locales/en/nsm/letters_and_calls.yml
- config/locales/en/nsm/work_items.yml
- spec/system/nsm/disbursements_spec.rb
- spec/system/nsm/letters_and_calls_spec.rb
- spec/system/nsm/work_items_spec.rb
- spec/view_models/nsm/v1/work_item_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1959)
> CRM457-1959: Standardise cost display

- config/feature_flags.yml
Reverts ministryofjustice/laa-assess-crime-forms#749
> Revert "CRM457-1907: Enable maintenance mode on prod"

- lib/tasks/fixes.rake
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1966)
> LAA ref fix: Use correct symbol referencing

- lib/tasks/fixes.rake
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1966)
> Fix Rake Task for Assess Mismatched References

- app/assets/stylesheets/custom/search.scss
- app/assets/stylesheets/local/moj.scss
- app/forms/search_form.rb
- app/javascript/application.js
- app/javascript/component/date-picker.js
- app/validators/is_a_date_validator.rb
- app/views/layouts/dashboard/_primary_navigation.html.erb
- app/views/layouts/nsm/_primary_navigation.html.erb
- app/views/layouts/prior_authority/_primary_navigation.html.erb
- app/views/shared/_search.html.erb
- config/initializers/date_and_time_formats.rb
- config/locales/en.yml
- config/locales/en/dashboards.yml
- config/locales/en/nsm/search.yml
- config/locales/en/prior_authority/search.yml
- spec/system/dashboards_spec.rb
- spec/system/nsm/search_spec.rb
- spec/system/prior_authority/search_spec.rb
Update search date selectors and amend copy
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1954)
Inline with designs
Similar for CRM4 and 7:
Similar for CRM4 and 7:
For Analytics dashboard search:
> CRM457-1954: Update search form design

- README.md
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1800)
> CRM457-1800: Update Readme for Maintenance Mode

- Gemfile.lock
https://security.snyk.io/vuln/SNYK-RUBY-PUMA-8062124
> update puma to 6.4.3

- Gemfile
- Gemfile.lock
- config/cache.yml
- config/environments/production.rb
- db/migrate/20240925081532_add_cache_table.rb
- db/schema.rb
Copy across same changes applied in provider
> CRM457-1755: Add solidcache in production

- .env.test
- app/controllers/nsm/send_backs_controller.rb
- app/forms/nsm/search_form.rb
- app/forms/nsm/send_back_form.rb
- app/helpers/application_helper.rb
- app/jobs/expire_sendbacks.rb
- app/jobs/nsm/fake_assess.rb
- app/mailers/nsm/feedback_messages/further_information_request_feedback.rb
- app/models/claim.rb
- app/services/working_day_service.rb
- app/view_models/nsm/v1/claim_summary.rb
- app/views/nsm/claim_details/show.html.erb
- app/views/nsm/histories/show.html.erb
- app/views/nsm/send_backs/edit.html.erb
- config/application.rb
- config/feature_flags.yml
- config/locales/en/events.yml
- config/locales/en/nsm/send_back.yml
- spec/controllers/nsm/send_backs_controller_spec.rb
- spec/forms/nsm/search_form_spec.rb
- spec/forms/nsm/send_back_form_spec.rb
- spec/jobs/expire_sendbacks_spec.rb
- spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
- spec/services/working_day_service_spec.rb
- spec/system/nsm/assessment_spec.rb
- spec/system/nsm/overview_spec.rb
- Update the send back form UI
- Add 'save and come back later'
- If the feature flag is enabled, add `further_information` and `resubmission_deadline` to the payload, working out resubmission deadline based on 10 working days in the future
- If the feature flag in enabled, use a different notify email template
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2002)
> CRM457-2000: New NSM send-back mechanism

- config/database.yml
- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1759)
> CRM457-1759: Require DB SSL for RDS

- app/views/shared/_search.html.erb
Make labels bold at bottom of search box
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2102)
> CRM457-2102: Add styling

- Gemfile
- Gemfile.lock
- app/services/notify_app_store/message_builder.rb
- spec/factories/prior_authority_applications.rb
- spec/forms/prior_authority/send_back_form_spec.rb
- spec/services/notify_app_store/message_builder_spec.rb
- spec/view_models/prior_authority/v1/application_details_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2096)
> CRM457-2096: Validate before submit and use realistic test data

- Gemfile
- Gemfile.lock
- app/services/notify_app_store/message_builder.rb
- spec/services/notify_app_store/message_builder_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2129)
> CRM457-2129: Validate NSM payloads

- helm_deploy/templates/ingress.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2152)
> CRM457-2152: Remove false positive

- app/controllers/nsm/claim_details_controller.rb
- app/controllers/nsm/send_backs_controller.rb
- app/models/event/new_version.rb
- app/models/nsm/event/send_back.rb
- app/views/nsm/claim_details/show.html.erb
- app/views/nsm/send_backs/show.html.erb
- config/locales/en/events.yml
- config/locales/en/nsm/claim_details.yml
- config/locales/en/nsm/send_back.yml
- config/routes.rb
- spec/controllers/nsm/claim_details_controller_spec.rb
- spec/controllers/nsm/send_backs_controller_spec.rb
- spec/models/event/send_back_spec.rb
- spec/system/nsm/assessment_spec.rb
- spec/system/nsm/history_spec.rb
- Update order of provider updates
- Add new confirmation screen after sending back
- Tweak event history
- Tweak overview UI
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1987)
> CRM457-1987: QA feedback

- db/pii.yml
- spec/models/pii_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2098)
> CRM457-2098: Add PII annotations

- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-uat.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2194)
You can check Metabase to ensure the correct dashboard are selected and configured correctly 
[Dev/UAT](https://uat.crime-forms-metabase.service.justice.gov.uk/dashboard/33-submission-by-service?date_filter=)
[Production](https://crime-forms-metabase.service.justice.gov.uk/dashboard/5-prior-authority-submission-by-service?submission_date=)
> CRM457-2194: Add additional dashboard to dev, uat and prod (Submission by Service)

- app/view_models/nsm/v1/disbursement.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2275)
> CRM-2275: Include VAT changes in changed? logic for disbursemrnts

- app/controllers/nsm/make_decisions_controller.rb
- app/forms/nsm/make_decision_form.rb
- app/forms/prior_authority/decision_form.rb
- app/views/nsm/claim_details/show.html.erb
- app/views/nsm/make_decisions/edit.html.erb
- app/views/prior_authority/decisions/new.html.erb
- config/locales/en/events.yml
- config/locales/en/nsm/claim_details.yml
- config/locales/en/nsm/make_decisions.yml
- config/locales/en/prior_authority/decisions.yml
- spec/system/nsm/assessment_spec.rb
- spec/system/prior_authority/make_decision_spec.rb
Share design of make a decision page between PA and NSM claims
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2148)
e2e tests fixed here https://github.com/ministryofjustice/nsm-e2e-test/pull/168
> [CMR457-2148] PA and NSM caseworker: amend 'make a decision' page

- app/models/claim.rb
- config/feature_flags.yml
> Ship youth court fee

- app/controllers/nsm/additional_fees_controller.rb
- app/forms/nsm/additional_fees_form.rb
- app/forms/nsm/youth_court_fee_form.rb
- app/view_models/nsm/v1/additional_fee.rb
- app/view_models/nsm/v1/additional_fees_summary.rb
- app/view_models/nsm/v1/core_cost_summary.rb
- app/view_models/nsm/v1/youth_court_fee.rb
- app/views/nsm/additional_fees/_adjusted.html.erb
- app/views/nsm/additional_fees/_index.html.erb
- app/views/nsm/additional_fees/edit.html.erb
- app/views/nsm/additional_fees/show.html.erb
- config/locales/en/nsm/additional_fees.yml
- config/locales/en/nsm/youth_court_fee_adjustments.yml
- spec/controllers/nsm/additional_fees_controller_spec.rb
- spec/system/nsm/additional_fees_spec.rb
- spec/view_models/base_view_model_spec.rb
- spec/view_models/nsm/v1/additional_fees_summary_spec.rb
- spec/view_models/nsm/v1/core_cost_summary_spec.rb
- spec/view_models/nsm/v1/youth_court_fee_spec.rb
Caseworkers needs to be able to review the new additional fee information and make appropriate an assessment.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2306)
> [CRM457-2306] NSM Caseworker: Adjust youth court fee

- app/controllers/concerns/nsm/adjustment_concern.rb
- app/controllers/nsm/additional_fees_controller.rb
- app/controllers/nsm/adjustments_controller.rb
- app/models/claim.rb
- app/services/nsm/adjustment_deleter.rb
- app/services/nsm/all_adjustments_deleter.rb
- app/view_models/nsm/v1/case_disposal.rb
- app/view_models/nsm/v1/youth_court_fee.rb
- app/views/nsm/additional_fees/_adjusted.html.erb
- app/views/nsm/additional_fees/confirm_delete_adjustment.html.erb
- app/views/nsm/letters_and_calls/_adjusted.html.erb
- config/locales/en/nsm/additional_fees.yml
- config/locales/en/nsm/adjustments.yml
- spec/factories/claims.rb
- spec/services/nsm/all_adjustments_deleter_spec.rb
- spec/system/nsm/additional_fees_spec.rb
- spec/system/nsm/adjustments_spec.rb
- spec/view_models/nsm/v1/case_disposal_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2300)
> CRM457-2300: Delete youth court adjustments

- config/locales/en.yml
- spec/system/nsm/overview_spec.rb
- spec/system/nsm/supporting_evidence_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2427)
> [CRM457-2427] update GDPR messaging

- app/view_models/nsm/v1/work_item.rb
- app/views/nsm/work_items/edit.html.erb
- app/views/nsm/work_items/show.html.erb
- config/locales/en/nsm/work_items.yml
- spec/system/nsm/assessment_spec.rb
- spec/system/nsm/work_items_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2417)
> CRM457-2417 NSM CW: Update the cost details for work items

- app/view_models/nsm/v1/letter_and_call.rb
- app/views/nsm/letters_and_calls/edit.html.erb
- app/views/nsm/letters_and_calls/show.html.erb
- config/locales/en/nsm/letters_and_calls.yml
- spec/system/nsm/letters_and_calls_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2419)
> CRM457-2419 Updates cost details for Letters and Calls

- app/view_models/nsm/v1/disbursement.rb
- app/views/nsm/disbursements/edit.html.erb
- app/views/nsm/disbursements/show.html.erb
- config/locales/en/nsm/disbursements.yml
- spec/system/nsm/assessment_spec.rb
- spec/system/nsm/disbursements_spec.rb
- spec/view_models/nsm/v1/disbursement_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2421)
> CRM457-2421  Updates cost details for Disbursements

- app/views/nsm/additional_fees/show.html.erb
- config/locales/en/nsm/additional_fees.yml
- spec/system/nsm/additional_fees_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2420)
> CRM457-2420 - Additional Fees

- helm_deploy/templates/ingress.yaml
We think this is too high now, so we're going to lower it to something
more realistic.
> Reduce anomaly threshold

- Dockerfile
> bump alpine 3.21 libxml2

- config/application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2593)
> CRM457-2593 update email domain

- Dockerfile
Use a mirror for the Alpine packages key
> Use a mirror for the Alpine packages key

- app/views/nsm/claims/_claim_summary.html.erb
- app/views/prior_authority/shared/_application_nav.html.erb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2636)
> CRM457-2636 change application status location

- app/views/nsm/supporting_evidences/show.html.erb
- config/locales/en/nsm/supporting_evidences.yml
[No ticket - thread](https://mojdt.slack.com/archives/C034YPREUSF/p1751446614046339)
> Change pagy item name to "item" for supporting evidence

- app/controllers/payments/requests_controller.rb
- app/controllers/payments/searches_controller.rb
- app/models/user.rb
- app/param_validators/payment_request_params.rb
- app/policies/payment_policy.rb
- app/view_models/payments/search_result.rb
- app/views/home/index.html.erb
- app/views/layouts/payments/_primary_navigation.html.erb
- app/views/payments/requests/index.html.erb
- config/locales/en.yml
- config/locales/en/assess_a_crime_form.yml
- config/locales/en/payments/payments.yml
- config/locales/en/payments/requests.yml
- config/routes.rb
- spec/controllers/payments/requests_controller_spec.rb
- spec/system/payments/requests_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2688)
> Add index page for payment requests
