ministryofjustice/laa-assess-crime-forms

app/models/event.rb, app/models/event/change_risk.rb, config/locales/en/events.yml, spec/models/event/change_risk_spec.rb
[Change risk: Add event into Claim history (CW)](https://dsdmoj.atlassian.net/browse/CRM457-517)
=> [CRM457-517] Adds change risk event to history

app/controllers/make_decisions_controller.rb, app/view_models/v1/laa_reference.rb, app/views/assessed_claims/index.html.erb, app/views/claims/index.html.erb, app/views/send_back/index.html.erb, app/views/shared/_claim_button_group.erb, app/views/shared/_pagination.html.erb, config/locales/en/make_decisions.yml, spec/controllers/make_decisions_controller_spec.rb
set update message after decision
- fix redirect
- fix some broke column classes
- fix turbo related issue with make decision screen
[CRM457-511](https://dsdmoj.atlassian.net/browse/CRM457-511)
[CRM457-511]: https://dsdmoj.atlassian.net/browse/CRM457-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRM457-511] Set update message when decision is made

app/controllers/change_risks_controller.rb, app/forms/change_risk_form.rb, app/views/change_risks/edit.html.erb, config/locales/en/change_risks.yml, config/locales/en/make_decisions.yml, spec/controllers/change_risks_controller_spec.rb, spec/forms/change_risk_form_spec.rb
set correct error messages for make decision screen
[CRM457-511](https://dsdmoj.atlassian.net/browse/CRM457-511)
[CRM457-511]: https://dsdmoj.atlassian.net/browse/CRM457-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-511 - Ensure we are using the correct error messaging

app/controllers/disbursements_controller.rb, app/controllers/letters_and_calls_controller.rb, app/controllers/supporting_evidences_controller.rb, app/controllers/work_items_controller.rb, app/view_models/base_view_model.rb, app/view_models/shared/work_item_summary.rb, app/view_models/v1/core_cost_summary.rb, app/view_models/v1/letters_and_calls_summary.rb, app/view_models/v1/travel_and_waiting.rb, spec/controllers/disbursements_controller_spec.rb, spec/controllers/letters_and_calls_controller_spec.rb, spec/controllers/supporting_evidences_controller_spec.rb, spec/controllers/work_items_controller_spec.rb, spec/view_models/base_view_model_spec.rb, spec/view_models/v1/core_cost_summary_spec.rb, spec/view_models/v1/letters_and_calls_summary_spec.rb, spec/view_models/v1/travel_and_waiting_spec.rb
Only a single way to build view models
This reduces the number of ways we do things.. which hopefully means stuff will be simplier
hopefully this make object building easier as there is now only a single way to do it... The next step is to add some documentation on how it all fits together
=> Crm457 621/event refactor 2

config/settings.yml, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Turn on Dev Auth in development environment so that real Azure authentication isn't being used
[Caseworker Build: Enable Dev Auth in Development](https://dsdmoj.atlassian.net/browse/CRM457-651)
=> Use Dev Auth in Development

app/controllers/letters_and_calls/uplifts_controller.rb, config/locales/en/letters_and_calls.yml
Add required flash notification when removing all uplift - letters and calls
[CRM457-624](https://dsdmoj.atlassian.net/browse/CRM457-624)
[CRM457-624]: https://dsdmoj.atlassian.net/browse/CRM457-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add flash message for remove all uplift

app/controllers/claims_controller.rb, app/controllers/your_claims_controller.rb, app/models/assignment.rb, app/models/claim.rb, app/models/event.rb, app/models/event/assignment.rb, app/models/event/unassignment.rb, app/view_models/v1/all_claims.rb, app/views/claims/_claim_summary.html.erb, app/views/your_claims/index.html.erb, config/locales/en/claims.yml, config/locales/en/your_claims.yml, config/routes.rb, db/migrate/20231102112118_create_assignments.rb, db/schema.rb, db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json, spec/controllers/claims_controller_spec.rb, spec/models/claims_spec.rb, spec/models/event/assignment_spec.rb, spec/models/event/unassignment_spec.rb, spec/view_models/v1/all_claims_spec.rb, spec/view_models/v1/contact_details_spec.rb, spec/view_models/v1/defendant_details_spec.rb, spec/view_models/v1/hearing_details_spec.rb
user assignment to claims
[CRM457-657](https://dsdmoj.atlassian.net/browse/CRM457-657)
User can now be assigned and unassigned from a claim, this:
* creates/deletes and Assignment record
* creates events that can be queries to determine if a user has been unassigned from a claim and hence can't be automatically reassigned
I was thinking a user should be unassigned when the claim is assess (i.e. marked as granted) as at this stage all the data is deleted meaning the Assignment record is just lost - something to think more about when we get to appeals/more info/etc...
[CRM457-657]: https://dsdmoj.atlassian.net/browse/CRM457-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-657 - User assignment

app/view_models/v1/disbursement.rb, app/views/disbursements/_disbursements_total.html.erb, app/views/disbursements/index.html.erb, config/locales/en/claims.yml, config/locales/en/disbursements.yml, spec/system/disbursements_spec.rb, spec/view_models/v1/disbursement_spec.rb
- Added a total table under Disbursement total
- Added a new column - Vat applied
- Renamed column 'Adjusted' to 'Caseworker allowed'
[CRM457-547](https://dsdmoj.atlassian.net/browse/CRM457-547)
[CRM457-547]: https://dsdmoj.atlassian.net/browse/CRM457-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRM457-547] Iterate disbursement adjustment tab

app/forms/make_decision_form.rb, app/helpers/application_helper.rb, app/models/event/decision.rb, app/services/receive_application_metadata.rb, app/view_models/v1/assessed_claims.rb, app/views/make_decisions/edit.html.erb, config/locales/en/assessed_claims.yml, config/locales/en/events.yml, config/locales/en/make_decisions.yml, spec/controllers/make_decisions_controller_spec.rb, spec/factories/events.rb, spec/forms/make_decision_form_spec.rb, spec/helpers/application_helper_spec.rb, spec/jobs/pull_latest_version_data_spec.rb, spec/models/event/decision_spec.rb, spec/models/event_spec.rb, spec/services/notify_app_store/message_builder_spec.rb, spec/view_models/base_view_model_spec.rb, spec/view_models/v1/assessed_claims_spec.rb
- Remove current version check for updating data
[Caseworker App Failing to Update from App Store When Schema Version Not 1](https://dsdmoj.atlassian.net/browse/CRM457-730)
=> Fix: Caseworker App Failing to Update from App Store When Schema Version Not 1

app/assets/stylesheets/custom/history-background.scss, app/views/histories/show.html.erb, app/views/supporting_evidences/show.html.erb
Add missing button from button of supporting evidence and history pages
[CRM457-775](https://dsdmoj.atlassian.net/browse/CRM457-775)
[CRM457-775]: https://dsdmoj.atlassian.net/browse/CRM457-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add missing button to evidence and history screens

db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json, db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
This is a suggestion on how VAT would be added to the JSON document
N/A
* `vat_rate` is stored on the top level of the JSON as this will make it easier to access
* `submitted_total_inc_vat` and `adjusted_total_inc_vat` are still populated when `vat_rate` is 0 (`vat_registered` is no)
* vat can still exist when `vat_registered` is no (from disbursements)
=> POC: expected JSON format for VAT

Gemfile.lock
Bump bundler 2.4.10 --> 2.4.22
latest bundler version - [changelog](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md)
=> Bump bundler 2.4.10 --> 2.4.22

spec/controllers/change_risks_controller_spec.rb, spec/controllers/histories_controller_spec.rb
Chore: handle param comparison deprecation
Fix the deprecation warnings from couple of tests
```shell
DEPRECATION WARNING: Comparing equality between `ActionController::Parameters` and a `Hash` is deprecated and will be removed in Rails 7.2. Please only do comparisons between instances of `ActionController::Parameters`. If you need to compare to a hash, first convert it using `ActionController::Parameters#new`. To disable the deprecated behavior set `Rails.application.config.action_controller.allow_deprecated_parameters_hash_equality = false`. (called from block (3 levels) in <top (required)> at .../spec/controllers/change_risks_controller_spec.rb:44)
DEPRECATION WARNING: Comparing equality between `ActionController::Parameters` and a `Hash` is deprecated and will be removed in Rails 7.2. …
```
=> Chore: handle param comparison deprecation

Gemfile, app/controllers/users/dev_auth_controller.rb, app/helpers/form_builder_helper.rb, app/models/concerns/auth_updateable.rb, app/models/concerns/reauthable.rb, bin/setup, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/content_security_policy.rb, config/initializers/devise.rb, config/initializers/filter_parameter_logging.rb, config/initializers/form_builder.rb, config/initializers/permissions_policy.rb, config/locales/en/claims.yml, config/puma.rb, spec/system/authenticating/dev_auth_spec.rb, spec/zeitwerk_spec.rb
Bump to use rails 7.1 defaults.
Keep upto date and so we can safely move to further rails bumps, such as 7.2
[CRM457-866](https://dsdmoj.atlassian.net/browse/CRM457-866)
Will need UATing manually
[CRM457-866]: https://dsdmoj.atlassian.net/browse/CRM457-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-866: bump rails defaults 7.0 to 7.1

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Handle error seen, possibly resulting from a data clearing exercise
```shell
undefined method `in_time_zone' for nil:NilClass (NoMethodError)
l(time_or_string.in_time_zone(LONDON_TIMEZONE), format:)
```
=> Handle nils for format_in_zone

helm_deploy/templates/deployment.yaml
CRM457-774: Workaround for Puma/k8s dropped request problem
Possible cause of bug [CRM457-774](https://dsdmoj.atlassian.net/browse/CRM457-774) but a good practice to handle
potentially avoid dropping requests anyway.
See: https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-774)
As long as config is parseable and we can deploy there is not much more we can test
[CRM457-774]: https://dsdmoj.atlassian.net/browse/CRM457-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-774: Workaround for Puma/k8s dropped request problem

.circleci/config.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
Output rspec results on CI and store coverage artifact
So we can see rspec failures on CI and store
coverage results for our perusal.
Came out of work on [CRM457-869](https://dsdmoj.atlassian.net/browse/CRM457-869) when trying to check coverage
You can see the coverage in the artifact tab on Circle CI. Just click coverage/index.html
**Failing test now visible**
**Coverage artifact available**
[CRM457-869]: https://dsdmoj.atlassian.net/browse/CRM457-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Output rspec results on CI and store coverage artifact

.circleci/config.yml
Fix browser tools issue
Chrome not installing with error:
```
chrome version major is 116
Installed version of Google Chrome is 116.0.5845.140
500
116.0.5845.140 will be installed
curl: (22) The requested URL returned error: 500
```
expected behaviour:
```
Chrome version major is 116
Installed version of Google Chrome is 116.0.5845.140
404
Matching Chrome Driver Version 404'd, falling back to first matching major version.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   864  100   864    0     0   8617      0 --:--:-- --:--:-- --:--:--  8640
New ChromeDriver version to be installed: 116.0.5845.96
116.0.5845.96 will be installed
^@^@ChromeDriver 116.0.5845.96 …
```
=> Fix browser tools issue

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Add missing security context to values
To handle warning:
```
W0226 11:53:29.208237     328 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "**************************************-worker" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "**************************************-worker" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "**************************************-worker" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "**************************************-worker" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0226 11:53:29.502009     328 warnings.go:70] would violate …
```
=> CI: Add missing security context to values

.env.development, Procfile.dev, README.md
- Hardcode default port in Procfile, inline with provider app's
- link to documentation in provider app for e2e setup
- Add env vars required for local e2e development
=> Document and add env vars required for local e2e development

config/locales/en/helpers.yml, spec/helpers/application_helper_spec.rb, spec/system/nsm/work_items_spec.rb, spec/system/prior_authority/adjustments_spec.rb, spec/system/prior_authority/view_adjust_quote_spec.rb, spec/view_models/nsm/v1/claim_details_spec.rb, spec/view_models/nsm/v1/travel_and_waiting_spec.rb, spec/view_models/nsm/v1/work_item_spec.rb, spec/view_models/prior_authority/v1/additional_cost_spec.rb
Change format period inline with prototype/designs
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-1204)
[came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
[and ticket](https://dsdmoj.atlassian.net/browse/CRM457-1115)
Came out of conversation with content and design who decided
that a consistent approach across NSM and PA on both caseworker
and provider app is preferred and should be
- full word for hours and minutes, lower case
- no leading zeros
=> CRM457-992: Change format period inline with prototype designs

helm_deploy/values-uat.yaml
Correct identifier for UAT ingress so that it includes the namespace 
[To fix this ](https://app.circleci.com/pipelines/github/ministryofjustice/laa-assess-crime-forms/1871/workflows/4bc4894b-cead-4fda-b295-55ae7bfe3b0c/jobs/11895)
=> Make indentifier for ingress valid (UAT)

app/view_models/prior_authority/v1/additional_cost.rb, app/view_models/prior_authority/v1/application_details/alternative_quote_card.rb, app/view_models/prior_authority/v1/application_details/primary_quote_card.rb, app/view_models/prior_authority/v1/application_summary.rb, app/view_models/prior_authority/v1/quote.rb, spec/system/prior_authority/view_applications_spec.rb, spec/view_models/prior_authority/v1/additional_cost_spec.rb
Update overview tab to display original/requested values
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-1220)
[link to parent ticket](https://dsdmoj.atlassian.net/browse/CRM457-1114)
Following the adjusted quotes work the overview page needs to 
ensure it shows the original provider supplied quote values
for the primary quote
=> CRM457-1114: update overview to show original values

app/controllers/prior_authority/adjustments_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/controllers/prior_authority/assignments_controller.rb, app/helpers/sortable_table_helper.rb, app/javascript/application.js, app/javascript/component/sortable_table.js, app/services/prior_authority/sorter.rb, app/view_models/prior_authority/v1/application_summary.rb, app/view_models/prior_authority/v1/table_row.rb, app/views/prior_authority/adjustments/_additional_costs.html.erb, app/views/prior_authority/adjustments/_service_costs.html.erb, app/views/prior_authority/adjustments/_travel_costs.erb, app/views/prior_authority/adjustments/index.html.erb, app/views/prior_authority/applications/_table.html.erb, app/views/prior_authority/applications/assessed.html.erb, app/views/prior_authority/applications/open.html.erb, app/views/prior_authority/applications/show.html.erb, config/locales/en/prior_authority/applications.yml, db/migrate/20240308150518_add_indexes_to_submissions.rb, db/schema.rb, spec/system/prior_authority/adjust_additional_costs_spec.rb, spec/system/prior_authority/adjust_service_costs_spec.rb, spec/system/prior_authority/adjust_travel_costs_spec.rb, spec/system/prior_authority/adjustments_spec.rb, spec/system/prior_authority/application_lists_spec.rb, spec/system/prior_authority/assign_applications_spec.rb, spec/system/prior_authority/view_adjust_quote_spec.rb
* The tickets refer to an 'in progress' state, so I've added that when an application is assigned to a caseworker
* Reuse the basic mechanism for sorting and pagination from provider app
* Stop using the  js-based MOJ sorting because we know it's not an appropriate solution (as doesn't consider pagination) and the JS was messing with this more thorough approach
* Implement readonly mode unless a user is assigned to the application and it is current 'in_progress'
[CRM457-1002](https://dsdmoj.atlassian.net/browse/)
[CRM457-1002]: https://dsdmoj.atlassian.net/browse/CRM457-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-1002: Add sortable lists of applications

.circleci/config.yml, Gemfile, lib/tasks/simplecov/process_coverage.rake, spec/rails_helper.rb, spec/services/app_store_token_provider_spec.rb, spec/spec_helper.rb
Extract coverage to separate job and collate results
Allow parallel test suite runs and separate test failures 
from coverage failures.
Also remove codeclimate because:
a. we have sonarcloud wired up which does a lot of the duplication and quality analysis already, 
b.  rubocop is already linting as part of the test suite,
c.  it clutters the circleci config with setup for it.
d. its never been in, or currently isn't in, provider app.
=> Extract coverage to separate job and collate

app/javascript/component/prior_authority/additional_cost_adjustment.js, app/javascript/component/prior_authority/service_cost_adjustment.js, app/javascript/component/prior_authority/travel_cost_adjustment.js, app/views/prior_authority/additional_costs/edit.html.erb, app/views/prior_authority/service_costs/edit.html.erb, app/views/prior_authority/travel_costs/edit.html.erb, config/locales/en/prior_authority/additional_costs.yml, config/locales/en/prior_authority/service_costs.yml, config/locales/en/prior_authority/travel_costs.yml, spec/system/prior_authority/adjust_additional_costs_spec.rb, spec/system/prior_authority/adjust_service_costs_spec.rb, spec/system/prior_authority/adjust_travel_costs_spec.rb
Do not display calculated adjustments on page load
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-1114)
Inline with prototype the adjustment forms should not
populate the "Adjusted cost" on page load but only on
clicking the "Calculate my changes" button.
=> CRM457-1114: Do not display calculated adjustments on page load

app/forms/base_adjustment_form.rb, app/forms/prior_authority/travel_cost_form.rb, app/javascript/component/nsm/work_item_adjustment.js, app/javascript/component/prior_authority/additional_cost_adjustment.js, app/javascript/component/prior_authority/cost_adjustment.js, app/javascript/component/prior_authority/service_cost_adjustment.js, app/javascript/component/prior_authority/travel_cost_adjustment.js, app/view_models/prior_authority/v1/quote.rb, app/views/prior_authority/adjustments/_additional_costs.html.erb, app/views/prior_authority/adjustments/_service_costs.html.erb, app/views/prior_authority/adjustments/_travel_costs.erb, app/views/prior_authority/adjustments/index.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/application_details.yml, lib/govuk_design_system_formbuilder/elements/period.rb, spec/system/prior_authority/adjust_additional_costs_spec.rb, spec/system/prior_authority/adjust_service_costs_spec.rb, spec/system/prior_authority/adjust_travel_costs_spec.rb, spec/system/prior_authority/view_adjust_quote_spec.rb
QA changes to "Adjust quotes" functionality
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
- Amend postcode field content
- Remove unnecessary padding on `hr` tag
- Add alpha character error handling for time period
- Handle NaN JS errors by displaying £ --
- Display adjustment comments on "Adjust quote" tab
Most significant change is the display of the explanation for each type of cost
=> CRM457-992: Changes from QA

app/controllers/prior_authority/related_applications_controller.rb, app/models/submission.rb, app/services/prior_authority/related_applications.rb, app/services/prior_authority/sorter.rb, app/view_models/prior_authority/v1/table_row.rb, app/views/prior_authority/related_applications/_table.html.erb, app/views/prior_authority/related_applications/index.html.erb, app/views/prior_authority/shared/_application_nav.html.erb, config/locales/en/prior_authority/applications.yml, config/locales/en/prior_authority/related_applications.yml, config/routes.rb, db/migrate/20240313095200_add_correct_indexes_to_submissions.rb, db/migrate/20240313120114_add_ufn_service_type_indexes_to_submission.rb, db/schema.rb, spec/factories/prior_authority_applications.rb, spec/system/prior_authority/view_related_applications_spec.rb
Add related applications
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-993)
Ordering/sorting has been amended as it did not appear to be working for client name. This should be retrospectively functional for assessed applications too. I have also amended the firm name sorting but not tested in this PR as that column is not used for related applications, only for assessed/open applications by the looks of the prototype.
In addition I have amended the table_row view model to include the firm_name and client_name methods as system tests
showed them to not be functioning, despite, weirdly, the client name working on the page in development. Still not sure why :(. Regardless it seemed sensible to explicitly rely on a defined `client_name` and `firm_name` method in the …
=> CRM457-993: Add related applications

app/forms/prior_authority/base_cost_adjustment_form.rb, app/validators/item_type_dependant_validator.rb, config/locales/en/errors.yml, spec/system/prior_authority/adjust_service_costs_spec.rb, spec/validators/item_type_dependant_validator_spec.rb
Add item cost error messages
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
Inline designs/content for error messages and QA feedback. This can/ should also be applied to provider
BLANK
ZERO
NOT A NUMBER
=> CRM457-992: Add item cost error messages

.circleci/config.yml
Move docker image scan to run in parrallel to tests
To reduce the timeoverhead since the scan takes as long or longer
than the test suite run.
=> Move docker image scan to run in parrallel to tests

app/controllers/prior_authority/events_controller.rb, app/forms/prior_authority/decision_form.rb, app/models/event.rb, app/models/event/draft_decision.rb, app/view_models/prior_authority/v1/event_summary.rb, app/views/prior_authority/events/index.html.erb, app/views/prior_authority/shared/_application_nav.html.erb, config/initializers/date_and_time_formats.rb, config/locales/en/prior_authority/events.yml, config/routes.rb, spec/system/prior_authority/history_spec.rb, spec/view_models/prior_authority/v1/event_summary_spec.rb
Add new application history page for PA, showing relevant events.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1005)
=> CRM457-1005: Prior authority application history

app/attributes/type/fully_validatable_integer.rb, app/forms/prior_authority/base_cost_adjustment_form.rb, app/views/prior_authority/additional_costs/_cost_fields.html.erb, app/views/prior_authority/service_costs/_cost_fields.html.erb, config/initializers/attribute_types.rb, spec/attributes/type/fully_validatable_integer_spec.rb, spec/system/prior_authority/adjust_additional_costs_spec.rb, spec/system/prior_authority/adjust_service_costs_spec.rb
Correct expected behaviour of `items` field for adjustments
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
From QA feedback and inline with forms in provider app, this changes the items field to be a text field that is
validated as an integer. This conforms to GDS standards as [covered in this blog](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)
=> CRM457-992: Correct expected behaviour of `items` field for adjustments

app/views/prior_authority/applications/assessed.html.erb, app/views/prior_authority/applications/open.html.erb, app/views/prior_authority/applications/your.html.erb, app/views/prior_authority/related_applications/index.html.erb
Correct no application content style
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-993)
Inline with QA feedback and retrospectivelly applied to Your, Open and Assessed application
pages too.
=> CRM457-993: correct no records content para

.circleci/config.yml
Automate deployment to prod for main
Until we go to private beta, and perhaps even after that,
we might as well deploy to UAT and then production automatically.
This will:
- expose any deployment issues immediatley on a per merge basis
- not incur overhead of devs remebering to deploy
=> Automate deployment to prod for main

app/forms/prior_authority/send_back_form.rb, config/application.rb, spec/forms/prior_authority/send_back_form_spec.rb
We already are sending almost everything we need to the app store when we send back an RFI. This PR just:
- Adds the resubmission deadline for display in provider UI as per the ticket
- Tidies up the code
- Adds tests to prove the right info is stored.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1186)
=> CRM457-1186: Add resubmission deadline

app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb, app/mailers/prior_authority/submission_feedback_mailer.rb, app/models/event.rb, spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
Add caseworker comments to further info request mailer
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-980)
Either on dev environment or locally using the assess dev api keys 
- create/update a caseworker application with your own email address as the providers email
- add your email to the govuk notify team members list
- assign the app to yourself as a case worker
- click the send back to provider on the app overview page
- add the comments
- Save and continue
=> CRM457-980: Add caseworker comments to further info request mailer

app/controllers/prior_authority/applications_controller.rb, app/forms/prior_authority/decision_form.rb, app/forms/prior_authority/send_back_form.rb, app/models/claim.rb, app/models/prior_authority_application.rb, app/models/submission.rb, app/services/prior_authority/choose_application_for_assignment.rb, app/view_models/prior_authority/v1/application_details.rb, app/view_models/prior_authority/v1/application_summary.rb, app/views/prior_authority/applications/show.html.erb, app/views/prior_authority/shared/_application_nav.html.erb, config/locales/en/prior_authority.yml, config/locales/en/prior_authority/applications.yml, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb, spec/system/prior_authority/view_applications_spec.rb, spec/system/prior_authority/view_related_applications_spec.rb
Adjust UI for showing applications to accommodate 'sent_back' state
Moved sent_back applications to the 'Open' table, not the 'Assessed' table
Tried to standardise naming around states. As these have now diverged quite a lot from NSM states, moved state-specific scopes into submission subclasses
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1187)
=> CRM457-1187: Tidy states and UI for showing sent back applications

app/mailers/prior_authority/feedback_messages/feedback_base.rb, spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb, spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb, spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb, spec/support/shared_examples/shared_claim_feedback_mailer.rb
Correct recipient for decision/RFI notifications
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-976)
Although a provider will be associated with an application
they also specify a solicitor case contact per application.
This contact should be used for notification purposes related
to the case.
=> CRM457-976: Correct recipient for decision/RFI notifications

Procfile.dev
Do not inline sidekiq for bin/dev
So it behaves as a hosted environments sidekiq worker
as expected and stats are updated.
without this the job will be processed inline with the side
effect that stats on the webui are not updated.
=> Do not inline sidekiq for bin/dev

app/controllers/nsm/send_backs_controller.rb, app/mailers/nsm/feedback_messages/feedback_base.rb, app/models/concerns/name_constructable.rb, app/view_models/base_view_model.rb, app/view_models/nsm/v1/all_claims.rb, app/view_models/nsm/v1/assessed_claims.rb, app/view_models/nsm/v1/claim_summary.rb, app/view_models/nsm/v1/contact_details.rb, app/view_models/nsm/v1/defendant_details.rb, app/view_models/nsm/v1/your_claims.rb, app/views/nsm/claims/_claim_summary.html.erb, db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json, db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json, spec/factories/claims.rb, spec/view_models/nsm/v1/all_claims_spec.rb, spec/view_models/nsm/v1/assessed_claims_spec.rb, spec/view_models/nsm/v1/claim_summary_spec.rb, spec/view_models/nsm/v1/defendant_details_spec.rb, spec/view_models/nsm/v1/your_claims_spec.rb
Provider now captures first name and last name for NSM defendants, and will shortly stop sending full_name. This prepares caseworker for that change
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1044)
=> CRM457-1044: Make name handling more flexible

app/mailers/nsm/feedback_messages/feedback_base.rb, app/mailers/nsm/feedback_messages/further_information_request_feedback.rb, app/mailers/nsm/feedback_messages/granted_feedback.rb, app/mailers/nsm/feedback_messages/part_granted_feedback.rb, app/mailers/nsm/feedback_messages/provider_request_feedback.rb, app/mailers/nsm/feedback_messages/rejected_feedback.rb, app/mailers/prior_authority/feedback_messages/feedback_base.rb, app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb, app/mailers/prior_authority/feedback_messages/granted_feedback.rb, app/mailers/prior_authority/feedback_messages/part_granted_feedback.rb, app/mailers/prior_authority/feedback_messages/rejected_feedback.rb, spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/nsm/feedback_messages/granted_feedback_spec.rb, spec/mailers/nsm/feedback_messages/part_granted_feedback_spec.rb, spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb, spec/mailers/nsm/feedback_messages/rejected_feedback_spec.rb, spec/mailers/nsm/submission_feedback_mailer_spec.rb, spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb, spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb, spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
Remove feedback URL from all notifications
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1033)
Inline with UCD discussion it was decided to remove feedback
links from notification emails sent by the service.
The templates have been edited on notify and no longer use it.
=> CRM457-1033: Remove feedback URL from all notifications

app/forms/prior_authority/send_back_form.rb, spec/forms/prior_authority/send_back_form_spec.rb
As discussed on slack, we're going to start populating a `further_information` array of hashes.
=> Put further information request in more useful format

app/views/prior_authority/applications/_primary_quote_card.html.erb, app/views/prior_authority/applications/show.html.erb
Came out of QA: when an application is not editable, the primary quote card shouldn't have a link offering to make adjustments.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-994)
=> Remove edit link when not editable

app/forms/base_adjustment_form.rb, app/forms/nsm/base_adjustment_form.rb, app/forms/prior_authority/base_cost_adjustment_form.rb, app/forms/prior_authority/travel_cost_form.rb, app/views/prior_authority/service_costs/edit.html.erb, config/locales/en/prior_authority/service_costs.yml, spec/system/prior_authority/adjust_service_costs_spec.rb
Remove "costs" suffix on h2 of service cost adjustment page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
QA feedback tweak
=> CRM457-992: QA feedback tweaks

app/controllers/prior_authority/additional_costs_controller.rb, app/controllers/prior_authority/service_costs_controller.rb, app/controllers/prior_authority/travel_costs_controller.rb, app/models/event/undo_edit.rb, app/services/prior_authority/adjustment_deleter.rb, app/view_models/prior_authority/additional_costs_with_adjustments.rb, app/view_models/prior_authority/service_costs_with_adjustments.rb, app/view_models/prior_authority/travel_costs_with_adjustments.rb, app/view_models/prior_authority/v1/quote.rb, app/views/prior_authority/adjustments/_additional_costs.html.erb, app/views/prior_authority/adjustments/_service_costs.html.erb, app/views/prior_authority/adjustments/_travel_costs.erb, app/views/prior_authority/shared/confirm_delete_adjustment.html.erb, config/locales/en/prior_authority/additional_costs.yml, config/locales/en/prior_authority/adjustments.yml, config/locales/en/prior_authority/confirm_deletion.yml, config/locales/en/prior_authority/service_costs.yml, config/locales/en/prior_authority/service_types.yml, config/locales/en/prior_authority/travel_costs.yml, config/routes.rb, spec/services/prior_authority/adjustment_deleter_spec.rb, spec/system/prior_authority/delete_adjustments_spec.rb
Mechanism to revert changes to service, travel and additional costs. Event history is preserved (a new undo event is created to reconcile event log changes with current values)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1235)
---
=> CRM457-1235: Delete adjustments

app/jobs/pull_latest_version_data.rb, app/models/event.rb, spec/jobs/pull_latest_version_data_spec.rb, spec/models/event_spec.rb
So that if we refactor classes in future we don't end up with data that refers to classes that no longer exist.
=> Stop referring to specific ruby classes in event payload

app/models/event.rb, spec/jobs/pull_latest_version_data_spec.rb
Events are immutable, so if we already have a record of an event we don't need to update it. But we do need not to try to recreate it, otherwise we end up with duplicates.
=> Do not try to save events we already have records of

app/view_models/nsm/v1/core_cost_summary.rb, app/views/nsm/adjustments/show.html.erb, app/views/nsm/claim_details/show.html.erb, app/views/nsm/letters_and_calls/index.html.erb, app/views/nsm/work_items/index.html.erb, config/locales/en/nsm/claims.yml, spec/system/accessibility_spec.rb, spec/view_models/nsm/v1/core_cost_summary_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-785)
This is only only part of the requirements on the ticket - the rest will be split out into a new tickets
This specifically implements:
* new core cost view at the top of the adjustments tab
* additional changes that have been strike-though in the list at the bottom
Now implemented:
* Updated Work items summary
* Updated Work items tables
* Anything not striked out in the list at then bottom
=> Crm457 785 core costs

helm_deploy/values-prod.yaml
[Update network policies so that Caseworker application talks to datastore via Cloud Platform rather than via an external url](https://dsdmoj.atlassian.net/browse/CRM457-1288)
The caseworker app image doesn't have curl so I can't test it using that - if anyone has any other ideas of how to run the request on the pod let me know, otherwise just trust me ;)
=> Use local app store service URL for production

helm_deploy/values-uat.yaml
[Update network policies so that Caseworker application talks to datastore via Cloud Platform rather than via an external url](https://dsdmoj.atlassian.net/browse/CRM457-1289)
This is just for the UAT env to use the local domain so ingress can be disabled in UAT also for an environment matching production more
=> Use Local App Store URL - UAT

.env.development, Procfile.dev
Add envars needed for local integration
This is one way of replicating a production like
integration of assess with app store inline with pub/sub
changes.
=> Add envars needed for local integration

app/forms/nsm/make_decision_form.rb, app/forms/nsm/send_back_form.rb, app/forms/prior_authority/decision_form.rb, app/forms/prior_authority/send_back_form.rb, app/jobs/expire_sendbacks.rb, app/mailers/prior_authority/submission_feedback_mailer.rb, app/services/notify_app_store.rb, app/services/update_submission.rb, config/application.rb, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, spec/forms/nsm/make_decision_form_spec.rb, spec/forms/nsm/send_back_form_spec.rb, spec/forms/prior_authority/send_back_form_spec.rb, spec/jobs/expire_sendbacks_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb, spec/services/notify_app_store_spec.rb, spec/services/update_submission_spec.rb, spec/system/nsm/assessment_spec.rb, spec/system/prior_authority/make_decision_spec.rb, spec/system/prior_authority/send_back_spec.rb
Add 'granted' email for auto-grants, and standardise how NotifyAppStore works to remove SNS stuff and now-unnecessary 30 second wait
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1318)
=> CRM457-1318: Auto grant email

app/controllers/sync_controller.rb, app/services/app_store_client.rb, spec/requests/sync_spec.rb, spec/services/app_store_client_spec.rb
Use `params[:data]` instead of re-pulling the data via a GET request
This means we can remove the `get_submission` app store call entirely, as we never use it.
=> Reduce app store calls

app/controllers/nsm/assessed_claims_controller.rb, app/controllers/nsm/claims_controller.rb, app/controllers/nsm/your_claims_controller.rb
Didn't notice first time round that all the NSM code is using pagy_array instead of pagy
=> Stop converting to arrays for pagination

app/services/notify_app_store.rb, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, spec/services/notify_app_store_spec.rb
E2E tests are now failing because they are trying to send an email and failing. We need to be able _not_ to try to send an email.
=> Only send emails if a flag is set

app/services/notify_app_store.rb, app/services/update_submission.rb, app/view_models/prior_authority/v1/application_details.rb, app/view_models/prior_authority/v1/application_details/further_information_card.rb, app/view_models/prior_authority/v1/event_summary.rb, app/views/prior_authority/applications/show.html.erb, app/views/prior_authority/events/index.html.erb, app/views/prior_authority/send_backs/show.html.erb, config/locales/en/prior_authority/events.yml, spec/system/prior_authority/send_back_spec.rb, spec/system/prior_authority/view_applications_spec.rb
- Reorder further information cards
- preserve paragraph breaks
- make sure there's a `br` between provider-provided text and first document link
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1012)
=> CRM457-1012: RFI tweaks from QA

.rubocop.yml, Gemfile, Gemfile.lock, app/jobs/nsm/fake_assess.rb, app/jobs/prior_authority/fake_assess.rb, app/view_models/nsm/v1/details_of_claim.rb, app/view_models/nsm/v1/equality_details.rb, lib/tasks/dummy_assessments.rake, spec/jobs/nsm/fake_assess_spec.rb, spec/jobs/prior_authority/fake_assess_spec.rb, spec/lib/tasks/dummy_assessments_spec.rb, spec/spec_helper.rb
Group assessable submissions into batches so that we don't have to worry about long-running jobs being interrupted
Randomise between all different outcomes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1284)
=> CRM457-1284: Add assessment fakery

app/models/claim.rb, app/views/shared/_claim_button_group.erb, spec/system/nsm/assessment_spec.rb
Hide send back button if claim is sent back
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1460)
=> CRM457-1460: Hide send back button if claim is sent back

.circleci/config.yml, .snyk
Add .snyk file for vulnerability ignores
The webui ignore mechanism does not appear to be working
plus this mechanism makes it simpler to manage in any event.
You can install the snyk cli locally following this
https://docs.snyk.io/snyk-cli/install-or-update-the-snyk-cli
or just `brew install snyk-cli`
See [how to create a snyk file locally](https://docs.snyk.io/manage-risk/prioritize-your-issues/the-.snyk-file)
TL;DR:
This command was run to generate a .snyk file to ignore this problematic vulnerability
```sh
snyk ignore --id=SNYK-JS-BRACES-6838727 --reason="no fix; no-impact" --expiry=2099-01-01
````
=> Add .snyk file for vulnerability ignores

app/forms/base_adjustment_form.rb, app/forms/nsm/disbursements_form.rb, app/forms/nsm/letters_calls_form.rb, app/forms/nsm/work_item_form.rb, app/views/about/feedback/index.html.erb, app/views/nsm/change_risks/edit.html.erb, app/views/nsm/disbursements/edit.html.erb, app/views/nsm/letters_and_calls/edit.html.erb, app/views/nsm/letters_and_calls/uplifts/edit.html.erb, app/views/nsm/make_decisions/edit.html.erb, app/views/nsm/send_backs/edit.html.erb, app/views/nsm/unassignments/edit.html.erb, app/views/nsm/work_items/edit.html.erb, app/views/nsm/work_items/uplifts/edit.html.erb, app/views/prior_authority/additional_costs/edit.html.erb, app/views/prior_authority/decisions/new.html.erb, app/views/prior_authority/manual_assignments/new.html.erb, app/views/prior_authority/send_backs/new.html.erb, app/views/prior_authority/service_costs/edit.html.erb, app/views/prior_authority/travel_costs/edit.html.erb, app/views/prior_authority/unassignments/new.html.erb, config/locales/en/nsm/disbursements.yml, config/locales/en/nsm/letters_and_calls.yml, config/locales/en/nsm/work_items.yml, spec/forms/nsm/letters_calls_form_spec.rb, spec/forms/nsm/work_item_form_spec.rb, spec/system/nsm/disbursements_spec.rb
- Move error summary to top of page across all forms
- Where we display a 'no change' error and there is only one field that is changeable, attach the error message to that field.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1423)
=> CRM457-1423: Move error messages and tie to a field if possible

app/helpers/application_helper.rb, app/views/nsm/claims/_claim_summary.html.erb, config/locales/en/nsm/claims.yml, spec/helpers/application_helper_spec.rb, spec/view_models/nsm/v1/claim_summary_spec.rb
Correct typo accessed -> assessed
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1463)
=> CRM457-1463: Correct typo accessed -> assessed 

app/view_models/nsm/v1/work_item.rb, spec/view_models/nsm/v1/core_cost_summary_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1467)
=> CRM457-1467: Use rationals instead of decimals to deal with recurring decimal imprecision

.snyk, package.json, yarn.lock
Bump braces 3.0.2 to 3.0.3 and unignore CVE warning
This fixes the CVE we currently ignore, designated
as SNYK-JS-BRACES-6838727.
If Snyk scan passes when the specific CVE is unignored then it is good to go. The snyk ignore has been left in as an example for future reference.
=> Bump braces 3.0.2 to 3.0.3

app/services/prior_authority/choose_application_for_assignment.rb, spec/services/prior_authority/choose_application_for_assignment_spec.rb
Amend "Get next" logic
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1551)
Inline with BA request the priority order should be as follows:
P1 - Oldest Date + Central Criminal Court (court type)
P2 - Oldest Date + Pathologist (service type)
P3 - Oldest Date
Note that "Oldest date" is the day, but same Priority levels on
the same day will need to also consider time. Time only matters after day
and court type/service type considered.
Examples:
- with two P1's on same day but one is older in time (A) than a newer (B) then A comes first?
- with a P1 (or P2) plus a P3 on the same day where P3 is older in time the P1 comes first?
=> CRM457-1551: Amend "Get next" logic

app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb, spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
CRM457-1565: Add subheadings in email for further info and incorrect info
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1565)
So providers/recipients can clearly tell what is requested
of them. Inline with content design QA reviews.
submit a PA with your email as a contact, in caseworker assign and "Send back to provider", select further info and amendment request.
=> CRM457-1565: Add subheadings in email for further info and incorrect info

db/migrate/20240308140314_create_autogrant_limits.csv, db/seeds.rb, db/seeds/autogrant_limits.rb, db/seeds/caseworkers.rb
Add "Back calculation" autogrant limits
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1549)
[Related bug fix ticket](https://dsdmoj.atlassian.net/browse/CRM457-1582)
It has been agreed with the BA that it can be autogranted.
Only one item (per_item unit_type only) can ever be claimed
at a rate less than or equal to the specified london/non-london
rates. all other scenarios for this service type will not be autogranted.
~~This is a less than ideal solution for implementing
autogrant for this service type.~~
~~It's implementation is pending discussion because
the service type is an outlier in a number of respects~~
~~- It is is implemented in provider as a variable hourly or item
base service type, requiring 2 autogrant limit records per service 
and start date (which …
=> CRM457-1549: Add "Back calculation" autogrant limits

db/migrate/20240605125438_seed_autogrant_limits.rb, db/schema.rb, run.sh
Run seeds on deploy 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1549)
For DEV branches db:prepare will run seeds when it first creates the database, but not thereafter. hosted envs will never run db:seeds as part of db:prepare so we add it explcitly. For local development we add amigration just to ensure developers have latest seeds locally. Seeds are idempotent so this should not matter.
- Run seeds on app start for hosted environments
- Add migration to [re]seed autogrant limits locally
Instead of the migration we could instead rely on developers to run db:seeds themselves locally but i quite like have the migration for historical reasons.
=> CRM457-1549: ensure seeds are run on hosted envs

app/forms/prior_authority/base_cost_adjustment_form.rb, app/forms/prior_authority/travel_cost_form.rb, app/validators/item_type_dependant_validator.rb, app/view_models/prior_authority/v1/application_details/primary_quote_card.rb, app/views/prior_authority/adjustments/index.html.erb, config/locales/en/errors.yml, spec/system/prior_authority/adjust_additional_costs_spec.rb, spec/system/prior_authority/adjust_service_costs_spec.rb, spec/validators/item_type_dependant_validator_spec.rb
- Travel time and additional cost time can be set to zero by caseworkers
- If travel time was positive but is now zero, still show the travel cost data on overview and adjustment screens
- Fix error messaging so that we only show 'must be more than zero' if zero is not allowed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1597)
=> CRM457-1597: Allow zero times

app/forms/prior_authority/base_cost_adjustment_form.rb, app/validators/cost_item_type_dependant_validator.rb, app/validators/item_type_dependant_validator.rb, spec/validators/cost_item_type_dependant_validator_spec.rb, spec/validators/item_type_dependant_validator_spec.rb
[Caseworker: Remove Coverage Skip for CostItemTypeDependantValidator](https://dsdmoj.atlassian.net/browse/CRM457-1620)
We do not use the pluralize feature and for cost item type validation and the way it was written for item type validation won't work as cost_item_type_for inputs into a translation - therefore, I removed that part of the code completely. If we need to use pluralize in the future, we can update appropriately
=> Remove coverage skip in CostItemTypeDependantValidator

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Add separate replica counts for app/web and worker
we do not need as many workers pods as app pods typically
but these should be seprate in any event.
=> Add separate replica counts for app/web and worker

helm_deploy/templates/ingress.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Instead of 3 copies of the same config, just use 1
Add the annotations that allow us to view modsec logs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1650)
=> CRM457-1650: Standardise modsec and add correct tagging

helm_deploy/templates/ingress.yaml
We have been experiencing some ModSec false positives, and we are aware of other teams experiencing them. This PR disables some of the more unreliable rules:
Civil Apply [found](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/3686039762/ModSecurity) that this was triggering if "a user ends a sentence with get and a single word, followed by a new line"
We [found](https://mojdt.slack.com/archives/C06UR7V28RZ/p1718890420747279) that this was triggering if a string in a JSON payload contained two consecutive pairs of parentheses, such as "...The preparation hourly rate has been reduced as per Schedule 1 of The Criminal Legal Aid (Remuneration)(Amendment) Regulations 2022..."
Crime Apply [found](https://github.com/ministryofjustice/cla_public/pull/1238) that this was triggering on a …
=> CRM457-1657: Remove some Modsec rules that give false positives

app/views/nsm/assignments/new.html.erb
We're rendering the primary nav twice on the assignment form for NSM
=> CRM457-1671: Remove duplicate nav

app/models/event.rb, app/models/event/assignment.rb, app/models/event/draft_decision.rb, app/models/event/new_version.rb, app/models/event/unassignment.rb, app/services/app_store_client.rb, app/services/notify_event_app_store.rb, db/migrate/20240625163719_send_missing_events.rb, db/schema.rb, spec/models/event/assignment_spec.rb, spec/models/event/new_version_spec.rb, spec/models/event/unassignment_spec.rb, spec/services/app_store_client_spec.rb, spec/services/notify_event_app_store_spec.rb
Push reportring events (Assignment, Unassignment and NewVersion to app store as they are created. Other events are synced once a decision/RFI request is made.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1665)
=> Crm457 1665/send eveents

Gemfile.lock, app/controllers/nsm/make_decisions_controller.rb, app/forms/nsm/make_decision_form.rb, app/views/nsm/make_decisions/edit.html.erb, config/locales/en/nsm/make_decisions.yml, spec/forms/nsm/make_decision_form_spec.rb, spec/system/nsm/assessment_spec.rb
Allow providers to enter a comment when granting a claim
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1676)
=> CRM457-1676: Optional grant comments

app/mailers/notify_mailer.rb, app/mailers/nsm/submission_feedback_mailer.rb, app/mailers/prior_authority/submission_feedback_mailer.rb, spec/mailers/nsm/submission_feedback_mailer_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb, spec/support/shared_examples/shared_claim_feedback_mailer.rb
Swallow team-only notification client errors on DEV/UAT
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1319)
When testing we often use invalid/non-team-member email addresses
and we are not interested in sentry or other alerting that results
from this on pre-prod environments
=> CRM457-1319: Swallow team-only notification client errors on DEV/UAT

config/schedule.yml
Change out of hours schedule for ExpireSendbacks job
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1706)
The ExpireSendbacks job needs to runs out of hours but when DEV/UAT
RDS instance is running.
On DEV/UAT this causes this errors and sidekiq dead jobs since RDS is
scheduled to be stopped between 22:00 to 06:00 UTC. The result is noisy
dead job alerts on DEV/UAT.
=> CRM457-1706: Change out of hours schedule for ExpireSendbacks job

app/jobs/nsm/fake_assess.rb, app/jobs/prior_authority/fake_assess.rb, lib/tasks/dummy_assessments.rake, spec/jobs/nsm/fake_assess_spec.rb, spec/jobs/prior_authority/fake_assess_spec.rb
Update the dummy assessment task so that it leaves some submissions as 'submitted' to allow for more varied test data, and also assigns a caseworker before assessing.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1714)
=> CRM457 -1714: Better dummy data

.circleci/config.yml, app/controllers/nsm/assignments_controller.rb, app/controllers/prior_authority/manual_assignments_controller.rb, app/controllers/prior_authority/unassignments_controller.rb, app/views/nsm/assignments/new.html.erb, app/views/prior_authority/manual_assignments/new.html.erb, app/views/prior_authority/unassignments/new.html.erb
Change snyk docker scanning approach
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1529)
This implements all but the IaC scan. The reason for not implementing IaC scanning now is:
- IaC needs rendered terraform or k8s manifests to scan, not helm templates
- attempts to render the manifests and pass them to the `snyk IaC test` hit various problems to do with helm install on test-executor (overcome), requiring k8s login for rendering the manifest (requiring cloud-platform-executor) or snyk install on cloud-platform-executor, and it has not been possible to test whether a helm upgrade --dry-run output would work. Certainly a `helm template blah` command as suggested by snyk docs is insufficient in our case. Ideally the cloud-platform-executor would have snyk installed …
=> CRM457-1529: Change snyk docker scanning approach

lib/tasks/db.rake, run.sh
Sometimes 2 pods run migrations at the same time, one loses the race, and we get error messages on Slack even though nothing bad has happened. This should prevent those false positives.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1672)
=> CRM457-1672: Concurrent migrations

.env.development, app/services/app_store_subscriber.rb, config/environments/production.rb, helm_deploy/templates/_helpers.tpl, helm_deploy/templates/deployment.yaml, spec/services/app_store_subscriber_spec.rb
By using the service URL instead of the host name associated with the ingress to construct our webhook url, we allow our app store -> caseworker HTTP requests to bypass modsec, which is good because modsec is notorious for false positives, and these requests should never be treated as a modsec positive.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1660)
I have adjusted our Cloud Platform permissions to allow internal network requests from the app store namespaces to the caseworker namespaces.
=> CRM457-1660: Use internal hostname to bypass modsec

.github/actions/delete-dev-release/action.yml, app/services/app_store_client.rb, app/services/app_store_subscriber.rb, config/application.rb, lib/tasks/app_store.rake, spec/lib/tasks/app_store_unsubscribe_spec.rb, spec/services/app_store_client_spec.rb, spec/services/app_store_subscriber_spec.rb
So that the app store stops trying to send notifications to deleted branches.
If this works I'll replicate on provider.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1368)
=> CRM457-1368: Unsub from app store on branch deletion

app/controllers/prior_authority/downloads_controller.rb, spec/system/prior_authority/view_applications_spec.rb
S3 craps out if the filename in the header has chars that don't conform to ISO-8859-1
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1744)
=> CRM457-1744: Fix for non-iso chars

app/forms/nsm/send_back_form.rb, spec/forms/nsm/send_back_form_spec.rb
Remove the assignment from a claim when it's send back. This brings claims in line with PA applications.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1749)
=> CRM457-1749: Sending back a claim removes assignments

helm_deploy/templates/ingress.yaml
951220, "mssql SQL Information Leakage"
Redundant because we don't use mssql. False positives happening in the wild (so far only on the app store metabase)
952100, "Java Source Code Leakage"
Redundant because we don't use Java. False positives happening on our javascript sourcemaps
=> CRM457-1721: More modsec false positives

app/view_models/nsm/v1/work_item.rb
When editing a work item, if the uplift is nil it doesn't display anything in the provider submission table.
Using type coercion, we can convert the false-y nil value to 0.
=> Return correct uplift when value is nil

app/forms/prior_authority/send_back_form.rb, spec/forms/prior_authority/send_back_form_spec.rb, spec/jobs/prior_authority/fake_assess_spec.rb, spec/services/sorters/work_items_sorter_spec.rb, spec/system/prior_authority/send_back_spec.rb
If I make adjustments then send an application back, those adjustments are effectively ignored, in that the provider app does not pick them up and when the provider app pushes a new version to the app store, those adjustments are overwritten anyway. BUT there's an unintended side effect, which is that when trying to work out which fields the provider has changed, the provider app diffs its database with the latest app store version. It picks up on the adjustments in the diff, with the end result that in the caseworker UI the fields the caseworker previously adjusted end up being highlighted as ones the _provider_ has adjusted in the RFI loop.
This PR undoes caseworker adjustments when an application is sent back, so that the version available in the app store has no adjustments, so the …
=> CRM457-1790: Discard  all adjustments prior to sending back

app/javascript/application.js, app/javascript/lib/table-item-anchors.js, app/views/nsm/disbursements/_adjusted.html.erb, app/views/nsm/disbursements/_index.html.erb, app/views/nsm/disbursements/edit.html.erb, app/views/nsm/disbursements/show.html.erb, app/views/nsm/work_items/_adjusted.html.erb, app/views/nsm/work_items/_index.html.erb, app/views/nsm/work_items/edit.html.erb, app/views/nsm/work_items/show.html.erb, spec/system/nsm/assessment_spec.rb
This enables a workflow of clicking on a work item or disbursement from a table and being able to navigate back directly to the row in question.
I've had to adjust the back buttons thanks to [how `link_to :back`](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to) interacts with the Content-Security-Policy, but if there's a nicer way to handle this then I'd love to know how.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1753)
=> [CRM457-1753] Ensure table rows act like anchors

app/models/event.rb, app/models/submission.rb, app/view_models/nsm/v1/table_row.rb, app/view_models/prior_authority/v1/application_summary.rb, app/view_models/prior_authority/v1/table_row.rb, app/view_models/search_result.rb, spec/system/prior_authority/view_applications_spec.rb
Alternative approach to https://github.com/ministryofjustice/laa-assess-crime-forms/pull/628. This will make 'last updated' almost entirely consistent with the app store value used to filter search results, while keeping it entirely consistent across the caseworker app.
I think the 'almost' above is such an extremely edgy edge case that it's ok for now, and the long-term solution is to pull data directly from the app store instead of a local database for all list and details views of applications.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1757)
=> CRM457-1757: Make sure "last updated" is accurate

db/migrate/20240807074430_backfill_disbursement_position.rb, db/schema.rb, lib/data_migration_tools/disbursement_position_updater.rb, spec/factories/disbursements.rb, spec/lib/data_migration_tools/disbursement_position_updater_spec.rb
Backfill NSM claim disbursements to have positions
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
Inline with designs on submit and app store for displaying
disbursements in a specific order.
Should be merged shortly after [this submit PR](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1039)
=> CMR457-1812: Backfill NSM claim disbursements to have positions

app/services/notify_app_store.rb, app/services/notify_event_app_store.rb
retry_on is part of the ActiveJob DSL that causes errors to be swallowed until a certain number of retries, after which the error is allowed to bubble up to the underlying mechanism (in our case Sidekiq, which will report the error to Sentry) This isn't actually the behaviour we want - if a job is failing we want Sentry to be informed immediately the first time it fails, on the grounds that normally this is going to be the indication of a problem, not some harmless transient error, so we want as much heads up as possible.
=> CRM457-1847: Remove 'retry_on'

app/forms/nsm/make_decision_form.rb, app/forms/nsm/send_back_form.rb, app/forms/prior_authority/decision_form.rb, app/forms/prior_authority/send_back_form.rb, app/services/update_submission.rb
Calling `perform_later` inside a transaction (including a lock) risks a race condition where the job might run before the transaction has been committed so will run using stale DB data. This can causing stale data to be sent to the app store, which is not ideal. This PR moves the perform_laters until after the transactions have been committed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1858)
=> Move perform_laters out of transactions to avoid race conditions

app/services/sorter.rb, spec/system/prior_authority/application_lists_spec.rb
Make sorting by last updated more sophisticated, so it matches how search results are sorted and how "last updated" is displayed in sortable table fields
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1866)
=> CRM457-1866: Better date sorting

app/views/nsm/letters_and_calls/_index.html.erb
remove duplicate header for letters and calls table
- this brings the letters and calls html inline with the work items and disbursements
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1846)
=> [CRM457-1846] Remove duplicated header

spec/system/nsm/overview_spec.rb
We previously had a broken view on the view part granted claim page, but our tests didn't pick it up because the page didn't render a section. We fixed the breakage [separately](https://github.com/ministryofjustice/laa-assess-crime-forms/commit/b21a76c589f573b3756987e3097b6cdb0925f652), this just adjusts the test to give us proper coverage.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1815)
=> CRM457-1815: Make test data more realistic to fix view coverage blind spot

app/controllers/nsm/searches_controller.rb, app/controllers/prior_authority/searches_controller.rb, app/forms/nsm/search_form.rb, app/forms/prior_authority/search_form.rb, app/views/dashboards/_tab_content.html.erb, app/views/nsm/searches/show.html.erb, app/views/prior_authority/searches/show.html.erb, app/views/shared/_search.html.erb, spec/forms/nsm/search_form_spec.rb, spec/system/nsm/search_spec.rb, spec/system/prior_authority/search_spec.rb
remove auto-grant filter from CRM7 search/filter
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1857)
i've namespaced the search_forms under their specific application types to absorb similar changes down the line.  If having these `search_form` in their own namespace seems more not less of a faff quite happy to replace this with a one-liner in `search_forms` 😅 
1. caseworker enter CRM7 search tab
2. select `status` select drop-down
=> CRM457-1857 remove auto-grants from select filter on CRM7 search/filter

app/models/claim.rb, app/view_models/nsm/v1/core_cost_summary.rb, app/views/nsm/review_and_adjusts/show.html.erb, spec/view_models/nsm/v1/core_cost_summary_spec.rb
Make unformatted totals available in CoreCostSummary so that we don't have to parse a string back to a float.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1895)
=> CRM457-1895: Resolve TODO

.rubocop.yml, app/javascript/lib/table-item-anchors.js, app/view_models/nsm/v1/core_cost_summary.rb, app/view_models/nsm/v1/work_item.rb, app/view_models/nsm/v1/work_item_summary.rb, app/views/nsm/work_items/_adjusted.html.erb, app/views/nsm/work_items/_index.html.erb, app/views/nsm/work_items/show.html.erb, config/locales/en/nsm/work_items.yml, spec/system/nsm/assessment_spec.rb, spec/system/nsm/work_items_spec.rb, spec/view_models/nsm/v1/core_cost_summary_spec.rb, spec/view_models/nsm/v1/work_item_spec.rb, spec/view_models/nsm/v1/work_items_summary_spec.rb
- Show all work types in work item summary
- Show asterisk in work item and core cost summary tables on row that no longer covers a work item because its work type has changed
- Add numbered footnotes to individual work item rows 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1871)
=> CRM457-1871: New UI for showing when work type changed

app/forms/nsm/disbursements_form.rb, config/locales/en/nsm/disbursements.yml, config/locales/en/nsm/letters_and_calls.yml, config/locales/en/nsm/work_items.yml
This changes disbursement adjustments to only compare against the values submitted since the last update rather than the original values.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1901)
=> CRM457-1901: Adjust how disbursement adjustments are validated

config/feature_flags.yml, helm_deploy/values-prod.yaml
Now that we have onboarded providers onto CRM7/Non-standard magistrate claims, caseworkers will need to be able to review analytics for these claims. 
To do this we need to enable the nsm_insights feature flag and add the relevant dashboards 
This PR: 
- Enables nsm_insights in production
- Adds the [Non-standard magistrate: submissions and resubmissions dashboard](https://crime-forms-metabase.service.justice.gov.uk/dashboard/4-non-standard-magistrates-submissions-and-resubmissions) to the analaytics tab
NOTE: this is draft because we still need to set up the production dashboard
=> Crm457 enable nsm insights

lib/tasks/fixes.rake, spec/factories/claims.rb, spec/lib/tasks/fixes_spec.rb
Add take task to update contact email address
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1909)
Part of documenting undeliverable email handling
=> CMR457-1909: Add rake task for contact email update

app/javascript/component/nsm/letters_calls_adjustment.js, app/view_models/nsm/v1/letter_and_call.rb, app/view_models/nsm/v1/work_item.rb, app/views/nsm/letters_and_calls/edit.html.erb, config/locales/en/nsm/letters_and_calls.yml, config/locales/en/nsm/work_items.yml, spec/view_models/nsm/v1/letter_and_call_spec.rb, spec/view_models/nsm/v1/work_item_spec.rb
We shouldn't show individual vat figures for work items or letters/calls, as VAT is only applied once things are summed up.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1946)
=> CRM457-1946: Remove individual VAT figures

spec/rails_helper.rb
Silence output to console from testing of rake tasks
Rake tasks often have stdout output but this comes
out when running rspec and clutters the console.
=> Swallow output to stdout during tests for rake tasks

config/feature_flags.yml
Enable maintance mode for PROD appstore DB upgrade 4/09/2024
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1907)
=> CRM457-1907: Enable maintenance mode on prod

app/services/prior_authority/choose_application_for_assignment.rb, spec/services/prior_authority/choose_application_for_assignment_spec.rb
Pathologist reports should only be prioritised if they relate to a post mortem
I also rewrote the logic explanation in the specs because I couldn't get my head around it without referring back to the video explanation.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1978)
=> CRM457-1978: Only prioritise post-mortem pathologist reports

app/javascript/application.js, app/views/home/index.html.erb, app/views/layouts/_header_navigation.html.erb, app/views/layouts/dashboard/_primary_navigation.html.erb, app/views/layouts/nsm/_primary_navigation.html.erb, app/views/layouts/prior_authority/_primary_navigation.html.erb, app/views/prior_authority/applications/_table.html.erb, app/views/prior_authority/shared/_application_buttons.html.erb, app/views/shared/_search.html.erb
Disable turbo-links generally
[bug ticket](https://dsdmoj.atlassian.net/browse/CRM457-2026)
[came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-1954)
More problems on search page due to turbolinks. When a sorting header column 
or pagination page link is clicked the date picker component is not initialised.
Rather than use more { data: turbo: false } for search, including the shared pagination
partial, and inline with this PR from submit i have disabled it entirely.
https://github.com/ministryofjustice/laa-submit-crime-forms/pull/688
Will do a manual regression test of potential impacted screens
=> CRM457-1954: Disable turbo-links

app/forms/nsm/search_form.rb, app/helpers/application_helper.rb, app/jobs/expire_sendbacks.rb, app/models/claim.rb, app/view_models/nsm/v1/claim_summary.rb, app/views/nsm/claim_details/show.html.erb, app/views/nsm/histories/show.html.erb, config/locales/en/events.yml, spec/forms/nsm/search_form_spec.rb, spec/jobs/expire_sendbacks_spec.rb, spec/system/nsm/overview_spec.rb
- Add logic to expire claims once the deadline has passed
- Show expired claims with appropriate UI
- The above meant adding a new status, and tidging how we group statuses, because 'expired' claims haven't been assessed but we want to treat them the same as assessed claims in some ways.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2002)
=> CRM457-2002: Expire claims and show expired claims

app/forms/nsm/send_back_form.rb, app/forms/prior_authority/send_back_form.rb, app/jobs/expire_sendbacks.rb, app/mailers/nsm/feedback_messages/further_information_request_feedback.rb, app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb, config/application.rb, spec/forms/prior_authority/send_back_form_spec.rb, spec/jobs/expire_sendbacks_spec.rb, spec/jobs/prior_authority/fake_assess_spec.rb, spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb, spec/mailers/prior_authority/submission_feedback_mailer_spec.rb, spec/system/prior_authority/send_back_spec.rb
Reuse the NSM "10 working day" logic for PA send-backs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2063)
=> CRM457-2063: Use 10 working day window for prior authority application send-backs

app/controllers/application_controller.rb, app/controllers/nsm/base_controller.rb, app/controllers/nsm/claims_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/controllers/prior_authority/base_controller.rb, app/models/access_log.rb, app/models/user.rb, db/migrate/20240930083741_create_access_logs.rb, db/schema.rb, lib/tasks/audit.rake, spec/controllers/nsm/change_risks_controller_spec.rb, spec/controllers/nsm/histories_controller_spec.rb, spec/controllers/nsm/make_decisions_controller_spec.rb, spec/controllers/nsm/send_backs_controller_spec.rb, spec/controllers/nsm/unassignments_controller_spec.rb, spec/factories/access_log.rb, spec/lib/tasks/audit_spec.rb, spec/system/nsm/assessment_spec.rb, spec/system/prior_authority/make_decision_spec.rb
Add access logs that are populated on every page view that involves looking at a submission
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1996)
- I've built in some redundancy in the log format, with both the full path and a breakdown of controller/action/id, to give us some protections against e.g. routes changing in future
- The rake task to spit out logs is very simple, in the absence of specific requirements I thought best to go with the easiest thing for now.
=> CRM457-1996: access logs

app/view_models/nsm/v1/further_information.rb, spec/view_models/nsm/v1/further_information_spec.rb
hotfix for when we might not have documents for further information - though this might actually just have been stray data in dev - an RFI send_back should always have an empty documents array that is populated by the provider on response if documents are added
=> HOTFIX for RFI nil documents 

app/services/nsm/all_adjustments_deleter.rb, spec/factories/claims.rb, spec/services/nsm/adjustment_deleter_spec.rb, spec/services/nsm/all_adjustments_deleter_spec.rb, spec/system/nsm/adjustments_spec.rb
This reverts commit 892d599b033366fe755961c33916c9c4b211838d.
Now when we click 'delete all adjustments' we manually remove every adjustment from the payload instead of pulling a 'fresh copy' from the app store. This is because the app store version may contain adjustments if we have completed an RFI loop and adjustments were made before the claim was sent back.
Robin had written code to do it this way initially, and I (wrongly!) said it was much simpler to take the 'fresh copy' approach.
=> CRM457-2049: Fix RFI/'delete all adjustments' edge case

app/view_models/nsm/v1/disbursement.rb, spec/view_models/nsm/v1/disbursement_spec.rb
"Other" can be a completely custom value, so we can't treat it as a standard translation
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2141)
=> CRM457-2141: Handle custom other types

app/mailers/prior_authority/feedback_messages/feedback_base.rb, app/mailers/prior_authority/feedback_messages/granted_feedback.rb, app/mailers/prior_authority/feedback_messages/part_granted_feedback.rb, spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb, spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2104)
Update Prior Authority Notify granted and part-granted emails to provider to include the Service required and the Service provider details.
=> [CRM457-2104] add service types to granted and part granted emails

app/forms/base_adjustment_form.rb, app/forms/nsm/uplift/base_form.rb, app/forms/prior_authority/travel_cost_form.rb, spec/forms/nsm/uplift/base_form_spec.rb, spec/forms/nsm/work_item_form_spec.rb
Keep previous comments on individual records when removing all uplifts.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2149)
=> CRM457-2149: Don't override adjustment comments when removing all uplifts

app/models/event.rb, app/services/notify_app_store.rb, app/services/notify_event_app_store.rb, db/migrate/20241015091931_add_notify_app_store_complete_to_submission.rb, db/schema.rb, spec/services/notify_app_store_spec.rb, spec/services/notify_event_app_store_spec.rb
Set a flag before running an async job, change the flag after running it, that way if we lose access to Redis (both the job queue and the logs of dead jobs), we know what needs to be re-synced.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2095)
=> CRM457-2095: Add flags indicating async job status

app/forms/nsm/make_decision_form.rb, app/forms/nsm/send_back_form.rb, app/forms/prior_authority/decision_form.rb, app/forms/prior_authority/send_back_form.rb, app/models/event.rb, app/models/event/new_version.rb, app/services/notify_app_store.rb, spec/models/event/new_version_spec.rb, spec/services/notify_app_store_spec.rb
This means if Redis fails we won't end up in an inconsistent state.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2094)
=> CRM457-2094: Make critical job enqueueings atomic

app/models/event.rb, app/models/role.rb, app/models/user.rb, db/migrate/20241015110647_create_roles.rb, db/schema.rb, db/seeds/caseworkers.rb, lib/tasks/custom_seeds.rake, lib/tasks/user.rake, spec/factories/role.rb, spec/factories/users.rb, spec/services/update_submission_spec.rb
Migrate roles to a has-many relationship so that we can accommodate things like some users having edit but not analytics access, some having analytics but not edit, and some having both.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2018)
=> CRM457-2018: Migrate roles to a has-many relationship

app/controllers/nsm/further_information_downloads_controller.rb, app/view_models/nsm/v1/further_information.rb, config/routes.rb, spec/system/nsm/overview_spec.rb, spec/view_models/nsm/v1/further_information_spec.rb
We were linking to the supporting evidence download path, but that only worked for documents listed as supporting evidence in the blob.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2183)
=> CRM457-2183: Allow downloading of RFI files

lib/tasks/fixes/CRM457_2220.rake
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2220)
This fix `un-sticks` application id `507c6b43-a3c5-4520-b610-b639b88c945c` for both CW and Provider by
- resetting CW status from expired to `sent_back`
- destroying the erroneous expired event from the application
- updating/resetting clock on resubmission_deadline (2 weeks from now)
- syncing changes with app-store/provider
we can run this fix by running `rake CRM457-2220:fix` 
Submission events for CW
```
[["Event::NewVersion", Fri, 11 Oct 2024 13:17:29.954099000 UTC +00:00],
["PriorAuthority::Event::SendBack", Mon, 14 Oct 2024 14:26:46.738524000 UTC +00:00],
["Event::Assignment", Mon, 14 Oct 2024 14:22:14.498403000 UTC +00:00],
["Event::ProviderUpdated", Mon, 14 Oct 2024 15:24:53.086000000 UTC +00:00], …
```
=> [CRM457-2220] un-stick expired provider application

app/view_models/nsm/v1/disbursement.rb
If a mileage-based disbursement has had the number of miles changed, then `total_cost_without_vat` will not change, as now that is only used to represent lump-sum disbursements, and we don't put a calculated total for miles * rate in there any more. So the only way to be confident that there has been a chance is to compare the total, vat-inclusive calculated result.
=> Fix disbursement change edge case

app/forms/prior_authority/unassignment_form.rb, app/models/event.rb, app/models/event/unassignment.rb, app/models/submission.rb, app/models/user.rb, app/view_models/nsm/v1/further_information.rb, app/view_models/prior_authority/v1/application_details/further_information_card.rb, app/view_models/prior_authority/v1/application_details/incorrect_information_card.rb, app/view_models/prior_authority/v1/application_summary.rb, app/view_models/search_result.rb, config/feature_flags.yml, config/locales/en/helpers.yml, spec/models/event/unassignment_spec.rb, spec/view_models/nsm/v1/further_information_spec.rb
- Switch off DevAuth on UAT to make it more secure
- Handle records imported from another env (where there will be unrecognised user IDs) better
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2322)
=> CRM457-2322: No UAT devauth, and improve UX when unknown caseworker ID

app/models/claim.rb
CoreCostSummary.show_allowed? calls `changed?` on a view model for every single work item and disbursement (can be hundreds), and each of those calls a calculator method with `submission.data_for_calculation` as an argument. This is a slow method when there are hundreds of work items and disbursements, so we can get a quick win by memoizing it so it only runs once per page load.
=> Memoize data_for_calculation

lib/tasks/user.rake, spec/lib/tasks/user_spec.rb, spec/rails_helper.rb
add a task to deactivate/reactivate users
deactivate a user`rake user:deactivate[email: test@test.com]`
reactivate a user `rake user:reactivate[email: test@test.com]`
confluence doc https://dsdmoj.atlassian.net/wiki/spaces/CRM457/pages/5354160130/Off-boarding+caseworkers+in+Users+in+Production+Environment
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2147)
=> CRM457-2147: add rake task to deactivate user

app/models/event/gdpr_documents_deleted.rb, config/locales/en/events.yml, spec/factories/events.rb, spec/system/nsm/history_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2416)
=> CRM457-2416: Add GDPR delete documents event to claim history

app/view_models/nsm/v1/disbursement.rb, spec/system/nsm/disbursements_spec.rb, spec/view_models/nsm/v1/disbursement_spec.rb
This pull request introduces changes to the `app/view_models/nsm/v1/disbursement.rb` file to improve the handling of VAT rates, as well as updates to the corresponding test files to ensure proper validation of the new functionality.
* [`app/view_models/nsm/v1/disbursement.rb`](diffhunk://#diff-620a1b52b7cf76cb0a718be014d360b5e323004dd3e9dff0097e33c5fa98aab4L69-R69): Modified the `format_vat_rate` method to accept an `original` parameter and added the `applicable_vat` method to determine the applicable VAT rate based on the `original` flag. [[1]](diffhunk://#diff-620a1b52b7cf76cb0a718be014d360b5e323004dd3e9dff0097e33c5fa98aab4L69-R69) [[2]](diffhunk://#diff-620a1b52b7cf76cb0a718be014d360b5e323004dd3e9dff0097e33c5fa98aab4L96-R105)
* …
=> CRM457-2422 Incorrect display of disbursement VAT rate

Gemfile.lock, app/forms/nsm/make_decision_form.rb, spec/forms/nsm/make_decision_form_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2546)
- Sets send_back_comment to nil before submitting decision to app store (subsequently to provider)
- Fixes invalid app store entry bug that occurs when using "Save and Come Back Later" on Send Back To Provider form and then making a decision
See reproduction steps in ticket
=> CRM457-2546: Reset Send Back Comment on Make Decision Form Submission

app/controllers/users_controller.rb, app/forms/user_form.rb, app/models/role.rb, app/models/user.rb, app/param_validators/users_params.rb, app/policies/claim_policy.rb, app/policies/prior_authority_application_policy.rb, app/policies/user_management_policy.rb, app/views/home/index.html.erb, app/views/users/_form.html.erb, app/views/users/_service.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb, config/locales/en.yml, config/locales/en/assess_a_crime_form.yml, config/locales/en/errors.yml, config/routes.rb, db/migrate/20250409140116_add_unique_constraint_to_user_email.rb, db/migrate/20250410083914_add_service_to_role.rb, db/pii.yml, db/schema.rb, db/seeds/caseworkers.rb, lib/tasks/user.rake, spec/factories/role.rb, spec/factories/users.rb, spec/models/event/unassignment_spec.rb, spec/system/nsm/history_spec.rb, spec/system/prior_authority/history_spec.rb, spec/system/users_spec.rb
Add a new UI to allow users to be managed outside of the now-deprecated rake task.
Also restricts which services caseworkers should be able to use.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2535)
This will need adjustments to how every other dev has their users
setup locally. If you're using the default seeded users, you won't
have to make any changes other than re-running `bundle exec db:seed`
again.
=> Add a user management UI

app/controllers/users/dev_auth_controller.rb, app/forms/user_form.rb, config/locales/en/errors.yml, spec/system/authenticating/dev_auth_spec.rb
- Only show active users in the `DevAuth` login prompt
- Ensure that a user must have a service
[Link to discussion](https://mojdt.slack.com/archives/C05212WRK5J/p1746714111788769)
=> Minor user UI changes

app/models/user.rb, app/policies/claim_policy.rb, app/policies/prior_authority_application_policy.rb
Policies against users run on every page and always go through a user's roles a few times. It only makes sense to compute this once per object lifetime.
[Link to relevant discussion](https://mojdt.slack.com/archives/C06UR7V28RZ/p1746802375906659)
=> Remove N+1 queries when loading user info

bin/deploy, helm_deploy/templates/_helpers.tpl, helm_deploy/templates/public-ingress.yaml
Remove the need to add Pingdom IPs to the whitelist by allowing the healthcheck endpoints to be public for GET requests only
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2628)
=>  Add public ingress to allow Pingdom to use without whitelist

app/views/layouts/_header_navigation.html.erb
[Change associated with this comment
](https://dsdmoj.atlassian.net/browse/CRM457-2635?focusedCommentId=617895)
=> CRM457-2635: Use correct class for Log Out link
